// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jk-zhang-meta/berth/ent/account"
	"github.com/jk-zhang-meta/berth/ent/predicate"
	"github.com/jk-zhang-meta/berth/ent/proxy"
)

// ProxyUpdate is the builder for updating Proxy entities.
type ProxyUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyMutation
}

// Where appends a list predicates to the ProxyUpdate builder.
func (_u *ProxyUpdate) Where(ps ...predicate.Proxy) *ProxyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUpdate) SetUpdatedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyUpdate) SetDeletedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableDeletedAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyUpdate) ClearDeletedAt() *ProxyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyUpdate) SetName(v string) *ProxyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableName(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProxyUpdate) SetProtocol(v string) *ProxyUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableProtocol(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *ProxyUpdate) SetHost(v string) *ProxyUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableHost(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ProxyUpdate) SetPort(v int) *ProxyUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillablePort(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ProxyUpdate) AddPort(v int) *ProxyUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *ProxyUpdate) SetUsername(v string) *ProxyUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableUsername(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *ProxyUpdate) ClearUsername() *ProxyUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetPassword sets the "password" field.
func (_u *ProxyUpdate) SetPassword(v string) *ProxyUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillablePassword(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *ProxyUpdate) ClearPassword() *ProxyUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyUpdate) SetStatus(v string) *ProxyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableStatus(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProxyUpdate) SetExpiresAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExpiresAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ProxyUpdate) ClearExpiresAt() *ProxyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetFallbackMode sets the "fallback_mode" field.
func (_u *ProxyUpdate) SetFallbackMode(v string) *ProxyUpdate {
	_u.mutation.SetFallbackMode(v)
	return _u
}

// SetNillableFallbackMode sets the "fallback_mode" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableFallbackMode(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetFallbackMode(*v)
	}
	return _u
}

// SetBackupProxyID sets the "backup_proxy_id" field.
func (_u *ProxyUpdate) SetBackupProxyID(v int64) *ProxyUpdate {
	_u.mutation.SetBackupProxyID(v)
	return _u
}

// SetNillableBackupProxyID sets the "backup_proxy_id" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableBackupProxyID(v *int64) *ProxyUpdate {
	if v != nil {
		_u.SetBackupProxyID(*v)
	}
	return _u
}

// ClearBackupProxyID clears the value of the "backup_proxy_id" field.
func (_u *ProxyUpdate) ClearBackupProxyID() *ProxyUpdate {
	_u.mutation.ClearBackupProxyID()
	return _u
}

// SetExpiryWarnDays sets the "expiry_warn_days" field.
func (_u *ProxyUpdate) SetExpiryWarnDays(v int) *ProxyUpdate {
	_u.mutation.ResetExpiryWarnDays()
	_u.mutation.SetExpiryWarnDays(v)
	return _u
}

// SetNillableExpiryWarnDays sets the "expiry_warn_days" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExpiryWarnDays(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetExpiryWarnDays(*v)
	}
	return _u
}

// AddExpiryWarnDays adds value to the "expiry_warn_days" field.
func (_u *ProxyUpdate) AddExpiryWarnDays(v int) *ProxyUpdate {
	_u.mutation.AddExpiryWarnDays(v)
	return _u
}

// SetExitIP sets the "exit_ip" field.
func (_u *ProxyUpdate) SetExitIP(v string) *ProxyUpdate {
	_u.mutation.SetExitIP(v)
	return _u
}

// SetNillableExitIP sets the "exit_ip" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitIP(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetExitIP(*v)
	}
	return _u
}

// ClearExitIP clears the value of the "exit_ip" field.
func (_u *ProxyUpdate) ClearExitIP() *ProxyUpdate {
	_u.mutation.ClearExitIP()
	return _u
}

// SetExitCountry sets the "exit_country" field.
func (_u *ProxyUpdate) SetExitCountry(v string) *ProxyUpdate {
	_u.mutation.SetExitCountry(v)
	return _u
}

// SetNillableExitCountry sets the "exit_country" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitCountry(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetExitCountry(*v)
	}
	return _u
}

// ClearExitCountry clears the value of the "exit_country" field.
func (_u *ProxyUpdate) ClearExitCountry() *ProxyUpdate {
	_u.mutation.ClearExitCountry()
	return _u
}

// SetExitCountryCode sets the "exit_country_code" field.
func (_u *ProxyUpdate) SetExitCountryCode(v string) *ProxyUpdate {
	_u.mutation.SetExitCountryCode(v)
	return _u
}

// SetNillableExitCountryCode sets the "exit_country_code" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitCountryCode(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetExitCountryCode(*v)
	}
	return _u
}

// ClearExitCountryCode clears the value of the "exit_country_code" field.
func (_u *ProxyUpdate) ClearExitCountryCode() *ProxyUpdate {
	_u.mutation.ClearExitCountryCode()
	return _u
}

// SetExitRegion sets the "exit_region" field.
func (_u *ProxyUpdate) SetExitRegion(v string) *ProxyUpdate {
	_u.mutation.SetExitRegion(v)
	return _u
}

// SetNillableExitRegion sets the "exit_region" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitRegion(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetExitRegion(*v)
	}
	return _u
}

// ClearExitRegion clears the value of the "exit_region" field.
func (_u *ProxyUpdate) ClearExitRegion() *ProxyUpdate {
	_u.mutation.ClearExitRegion()
	return _u
}

// SetExitCity sets the "exit_city" field.
func (_u *ProxyUpdate) SetExitCity(v string) *ProxyUpdate {
	_u.mutation.SetExitCity(v)
	return _u
}

// SetNillableExitCity sets the "exit_city" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitCity(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetExitCity(*v)
	}
	return _u
}

// ClearExitCity clears the value of the "exit_city" field.
func (_u *ProxyUpdate) ClearExitCity() *ProxyUpdate {
	_u.mutation.ClearExitCity()
	return _u
}

// SetExitTimezone sets the "exit_timezone" field.
func (_u *ProxyUpdate) SetExitTimezone(v string) *ProxyUpdate {
	_u.mutation.SetExitTimezone(v)
	return _u
}

// SetNillableExitTimezone sets the "exit_timezone" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitTimezone(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetExitTimezone(*v)
	}
	return _u
}

// ClearExitTimezone clears the value of the "exit_timezone" field.
func (_u *ProxyUpdate) ClearExitTimezone() *ProxyUpdate {
	_u.mutation.ClearExitTimezone()
	return _u
}

// SetExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field.
func (_u *ProxyUpdate) SetExitUtcOffsetSeconds(v int) *ProxyUpdate {
	_u.mutation.ResetExitUtcOffsetSeconds()
	_u.mutation.SetExitUtcOffsetSeconds(v)
	return _u
}

// SetNillableExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitUtcOffsetSeconds(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetExitUtcOffsetSeconds(*v)
	}
	return _u
}

// AddExitUtcOffsetSeconds adds value to the "exit_utc_offset_seconds" field.
func (_u *ProxyUpdate) AddExitUtcOffsetSeconds(v int) *ProxyUpdate {
	_u.mutation.AddExitUtcOffsetSeconds(v)
	return _u
}

// ClearExitUtcOffsetSeconds clears the value of the "exit_utc_offset_seconds" field.
func (_u *ProxyUpdate) ClearExitUtcOffsetSeconds() *ProxyUpdate {
	_u.mutation.ClearExitUtcOffsetSeconds()
	return _u
}

// SetExitAsn sets the "exit_asn" field.
func (_u *ProxyUpdate) SetExitAsn(v string) *ProxyUpdate {
	_u.mutation.SetExitAsn(v)
	return _u
}

// SetNillableExitAsn sets the "exit_asn" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitAsn(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetExitAsn(*v)
	}
	return _u
}

// ClearExitAsn clears the value of the "exit_asn" field.
func (_u *ProxyUpdate) ClearExitAsn() *ProxyUpdate {
	_u.mutation.ClearExitAsn()
	return _u
}

// SetExitIsp sets the "exit_isp" field.
func (_u *ProxyUpdate) SetExitIsp(v string) *ProxyUpdate {
	_u.mutation.SetExitIsp(v)
	return _u
}

// SetNillableExitIsp sets the "exit_isp" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitIsp(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetExitIsp(*v)
	}
	return _u
}

// ClearExitIsp clears the value of the "exit_isp" field.
func (_u *ProxyUpdate) ClearExitIsp() *ProxyUpdate {
	_u.mutation.ClearExitIsp()
	return _u
}

// SetExitCheckedAt sets the "exit_checked_at" field.
func (_u *ProxyUpdate) SetExitCheckedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetExitCheckedAt(v)
	return _u
}

// SetNillableExitCheckedAt sets the "exit_checked_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExitCheckedAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetExitCheckedAt(*v)
	}
	return _u
}

// ClearExitCheckedAt clears the value of the "exit_checked_at" field.
func (_u *ProxyUpdate) ClearExitCheckedAt() *ProxyUpdate {
	_u.mutation.ClearExitCheckedAt()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *ProxyUpdate) AddAccountIDs(ids ...int64) *ProxyUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *ProxyUpdate) AddAccounts(v ...*Account) *ProxyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddPrimaryProxyIDs adds the "primary_proxies" edge to the Proxy entity by IDs.
func (_u *ProxyUpdate) AddPrimaryProxyIDs(ids ...int64) *ProxyUpdate {
	_u.mutation.AddPrimaryProxyIDs(ids...)
	return _u
}

// AddPrimaryProxies adds the "primary_proxies" edges to the Proxy entity.
func (_u *ProxyUpdate) AddPrimaryProxies(v ...*Proxy) *ProxyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrimaryProxyIDs(ids...)
}

// SetBackupProxy sets the "backup_proxy" edge to the Proxy entity.
func (_u *ProxyUpdate) SetBackupProxy(v *Proxy) *ProxyUpdate {
	return _u.SetBackupProxyID(v.ID)
}

// Mutation returns the ProxyMutation object of the builder.
func (_u *ProxyUpdate) Mutation() *ProxyMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *ProxyUpdate) ClearAccounts() *ProxyUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *ProxyUpdate) RemoveAccountIDs(ids ...int64) *ProxyUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *ProxyUpdate) RemoveAccounts(v ...*Account) *ProxyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearPrimaryProxies clears all "primary_proxies" edges to the Proxy entity.
func (_u *ProxyUpdate) ClearPrimaryProxies() *ProxyUpdate {
	_u.mutation.ClearPrimaryProxies()
	return _u
}

// RemovePrimaryProxyIDs removes the "primary_proxies" edge to Proxy entities by IDs.
func (_u *ProxyUpdate) RemovePrimaryProxyIDs(ids ...int64) *ProxyUpdate {
	_u.mutation.RemovePrimaryProxyIDs(ids...)
	return _u
}

// RemovePrimaryProxies removes "primary_proxies" edges to Proxy entities.
func (_u *ProxyUpdate) RemovePrimaryProxies(v ...*Proxy) *ProxyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrimaryProxyIDs(ids...)
}

// ClearBackupProxy clears the "backup_proxy" edge to the Proxy entity.
func (_u *ProxyUpdate) ClearBackupProxy() *ProxyUpdate {
	_u.mutation.ClearBackupProxy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := proxy.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Proxy.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := proxy.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Proxy.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := proxy.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Proxy.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := proxy.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Proxy.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Proxy.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FallbackMode(); ok {
		if err := proxy.FallbackModeValidator(v); err != nil {
			return &ValidationError{Name: "fallback_mode", err: fmt.Errorf(`ent: validator failed for field "Proxy.fallback_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitIP(); ok {
		if err := proxy.ExitIPValidator(v); err != nil {
			return &ValidationError{Name: "exit_ip", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitCountry(); ok {
		if err := proxy.ExitCountryValidator(v); err != nil {
			return &ValidationError{Name: "exit_country", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitCountryCode(); ok {
		if err := proxy.ExitCountryCodeValidator(v); err != nil {
			return &ValidationError{Name: "exit_country_code", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_country_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitRegion(); ok {
		if err := proxy.ExitRegionValidator(v); err != nil {
			return &ValidationError{Name: "exit_region", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitCity(); ok {
		if err := proxy.ExitCityValidator(v); err != nil {
			return &ValidationError{Name: "exit_city", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitTimezone(); ok {
		if err := proxy.ExitTimezoneValidator(v); err != nil {
			return &ValidationError{Name: "exit_timezone", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitAsn(); ok {
		if err := proxy.ExitAsnValidator(v); err != nil {
			return &ValidationError{Name: "exit_asn", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_asn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitIsp(); ok {
		if err := proxy.ExitIspValidator(v); err != nil {
			return &ValidationError{Name: "exit_isp", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_isp": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxy.Table, proxy.Columns, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxy.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxy.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxy.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(proxy.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(proxy.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(proxy.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(proxy.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxy.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(proxy.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(proxy.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FallbackMode(); ok {
		_spec.SetField(proxy.FieldFallbackMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiryWarnDays(); ok {
		_spec.SetField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpiryWarnDays(); ok {
		_spec.AddField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExitIP(); ok {
		_spec.SetField(proxy.FieldExitIP, field.TypeString, value)
	}
	if _u.mutation.ExitIPCleared() {
		_spec.ClearField(proxy.FieldExitIP, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCountry(); ok {
		_spec.SetField(proxy.FieldExitCountry, field.TypeString, value)
	}
	if _u.mutation.ExitCountryCleared() {
		_spec.ClearField(proxy.FieldExitCountry, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCountryCode(); ok {
		_spec.SetField(proxy.FieldExitCountryCode, field.TypeString, value)
	}
	if _u.mutation.ExitCountryCodeCleared() {
		_spec.ClearField(proxy.FieldExitCountryCode, field.TypeString)
	}
	if value, ok := _u.mutation.ExitRegion(); ok {
		_spec.SetField(proxy.FieldExitRegion, field.TypeString, value)
	}
	if _u.mutation.ExitRegionCleared() {
		_spec.ClearField(proxy.FieldExitRegion, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCity(); ok {
		_spec.SetField(proxy.FieldExitCity, field.TypeString, value)
	}
	if _u.mutation.ExitCityCleared() {
		_spec.ClearField(proxy.FieldExitCity, field.TypeString)
	}
	if value, ok := _u.mutation.ExitTimezone(); ok {
		_spec.SetField(proxy.FieldExitTimezone, field.TypeString, value)
	}
	if _u.mutation.ExitTimezoneCleared() {
		_spec.ClearField(proxy.FieldExitTimezone, field.TypeString)
	}
	if value, ok := _u.mutation.ExitUtcOffsetSeconds(); ok {
		_spec.SetField(proxy.FieldExitUtcOffsetSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExitUtcOffsetSeconds(); ok {
		_spec.AddField(proxy.FieldExitUtcOffsetSeconds, field.TypeInt, value)
	}
	if _u.mutation.ExitUtcOffsetSecondsCleared() {
		_spec.ClearField(proxy.FieldExitUtcOffsetSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.ExitAsn(); ok {
		_spec.SetField(proxy.FieldExitAsn, field.TypeString, value)
	}
	if _u.mutation.ExitAsnCleared() {
		_spec.ClearField(proxy.FieldExitAsn, field.TypeString)
	}
	if value, ok := _u.mutation.ExitIsp(); ok {
		_spec.SetField(proxy.FieldExitIsp, field.TypeString, value)
	}
	if _u.mutation.ExitIspCleared() {
		_spec.ClearField(proxy.FieldExitIsp, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCheckedAt(); ok {
		_spec.SetField(proxy.FieldExitCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.ExitCheckedAtCleared() {
		_spec.ClearField(proxy.FieldExitCheckedAt, field.TypeTime)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrimaryProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.PrimaryProxiesTable,
			Columns: []string{proxy.PrimaryProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrimaryProxiesIDs(); len(nodes) > 0 && !_u.mutation.PrimaryProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.PrimaryProxiesTable,
			Columns: []string{proxy.PrimaryProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrimaryProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.PrimaryProxiesTable,
			Columns: []string{proxy.PrimaryProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BackupProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BackupProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyUpdateOne is the builder for updating a single Proxy entity.
type ProxyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUpdateOne) SetUpdatedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyUpdateOne) SetDeletedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableDeletedAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyUpdateOne) ClearDeletedAt() *ProxyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyUpdateOne) SetName(v string) *ProxyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableName(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProxyUpdateOne) SetProtocol(v string) *ProxyUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableProtocol(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *ProxyUpdateOne) SetHost(v string) *ProxyUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableHost(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ProxyUpdateOne) SetPort(v int) *ProxyUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillablePort(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ProxyUpdateOne) AddPort(v int) *ProxyUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *ProxyUpdateOne) SetUsername(v string) *ProxyUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableUsername(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *ProxyUpdateOne) ClearUsername() *ProxyUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetPassword sets the "password" field.
func (_u *ProxyUpdateOne) SetPassword(v string) *ProxyUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillablePassword(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *ProxyUpdateOne) ClearPassword() *ProxyUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyUpdateOne) SetStatus(v string) *ProxyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableStatus(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProxyUpdateOne) SetExpiresAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExpiresAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ProxyUpdateOne) ClearExpiresAt() *ProxyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetFallbackMode sets the "fallback_mode" field.
func (_u *ProxyUpdateOne) SetFallbackMode(v string) *ProxyUpdateOne {
	_u.mutation.SetFallbackMode(v)
	return _u
}

// SetNillableFallbackMode sets the "fallback_mode" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableFallbackMode(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetFallbackMode(*v)
	}
	return _u
}

// SetBackupProxyID sets the "backup_proxy_id" field.
func (_u *ProxyUpdateOne) SetBackupProxyID(v int64) *ProxyUpdateOne {
	_u.mutation.SetBackupProxyID(v)
	return _u
}

// SetNillableBackupProxyID sets the "backup_proxy_id" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableBackupProxyID(v *int64) *ProxyUpdateOne {
	if v != nil {
		_u.SetBackupProxyID(*v)
	}
	return _u
}

// ClearBackupProxyID clears the value of the "backup_proxy_id" field.
func (_u *ProxyUpdateOne) ClearBackupProxyID() *ProxyUpdateOne {
	_u.mutation.ClearBackupProxyID()
	return _u
}

// SetExpiryWarnDays sets the "expiry_warn_days" field.
func (_u *ProxyUpdateOne) SetExpiryWarnDays(v int) *ProxyUpdateOne {
	_u.mutation.ResetExpiryWarnDays()
	_u.mutation.SetExpiryWarnDays(v)
	return _u
}

// SetNillableExpiryWarnDays sets the "expiry_warn_days" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExpiryWarnDays(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetExpiryWarnDays(*v)
	}
	return _u
}

// AddExpiryWarnDays adds value to the "expiry_warn_days" field.
func (_u *ProxyUpdateOne) AddExpiryWarnDays(v int) *ProxyUpdateOne {
	_u.mutation.AddExpiryWarnDays(v)
	return _u
}

// SetExitIP sets the "exit_ip" field.
func (_u *ProxyUpdateOne) SetExitIP(v string) *ProxyUpdateOne {
	_u.mutation.SetExitIP(v)
	return _u
}

// SetNillableExitIP sets the "exit_ip" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitIP(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitIP(*v)
	}
	return _u
}

// ClearExitIP clears the value of the "exit_ip" field.
func (_u *ProxyUpdateOne) ClearExitIP() *ProxyUpdateOne {
	_u.mutation.ClearExitIP()
	return _u
}

// SetExitCountry sets the "exit_country" field.
func (_u *ProxyUpdateOne) SetExitCountry(v string) *ProxyUpdateOne {
	_u.mutation.SetExitCountry(v)
	return _u
}

// SetNillableExitCountry sets the "exit_country" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitCountry(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitCountry(*v)
	}
	return _u
}

// ClearExitCountry clears the value of the "exit_country" field.
func (_u *ProxyUpdateOne) ClearExitCountry() *ProxyUpdateOne {
	_u.mutation.ClearExitCountry()
	return _u
}

// SetExitCountryCode sets the "exit_country_code" field.
func (_u *ProxyUpdateOne) SetExitCountryCode(v string) *ProxyUpdateOne {
	_u.mutation.SetExitCountryCode(v)
	return _u
}

// SetNillableExitCountryCode sets the "exit_country_code" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitCountryCode(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitCountryCode(*v)
	}
	return _u
}

// ClearExitCountryCode clears the value of the "exit_country_code" field.
func (_u *ProxyUpdateOne) ClearExitCountryCode() *ProxyUpdateOne {
	_u.mutation.ClearExitCountryCode()
	return _u
}

// SetExitRegion sets the "exit_region" field.
func (_u *ProxyUpdateOne) SetExitRegion(v string) *ProxyUpdateOne {
	_u.mutation.SetExitRegion(v)
	return _u
}

// SetNillableExitRegion sets the "exit_region" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitRegion(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitRegion(*v)
	}
	return _u
}

// ClearExitRegion clears the value of the "exit_region" field.
func (_u *ProxyUpdateOne) ClearExitRegion() *ProxyUpdateOne {
	_u.mutation.ClearExitRegion()
	return _u
}

// SetExitCity sets the "exit_city" field.
func (_u *ProxyUpdateOne) SetExitCity(v string) *ProxyUpdateOne {
	_u.mutation.SetExitCity(v)
	return _u
}

// SetNillableExitCity sets the "exit_city" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitCity(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitCity(*v)
	}
	return _u
}

// ClearExitCity clears the value of the "exit_city" field.
func (_u *ProxyUpdateOne) ClearExitCity() *ProxyUpdateOne {
	_u.mutation.ClearExitCity()
	return _u
}

// SetExitTimezone sets the "exit_timezone" field.
func (_u *ProxyUpdateOne) SetExitTimezone(v string) *ProxyUpdateOne {
	_u.mutation.SetExitTimezone(v)
	return _u
}

// SetNillableExitTimezone sets the "exit_timezone" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitTimezone(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitTimezone(*v)
	}
	return _u
}

// ClearExitTimezone clears the value of the "exit_timezone" field.
func (_u *ProxyUpdateOne) ClearExitTimezone() *ProxyUpdateOne {
	_u.mutation.ClearExitTimezone()
	return _u
}

// SetExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field.
func (_u *ProxyUpdateOne) SetExitUtcOffsetSeconds(v int) *ProxyUpdateOne {
	_u.mutation.ResetExitUtcOffsetSeconds()
	_u.mutation.SetExitUtcOffsetSeconds(v)
	return _u
}

// SetNillableExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitUtcOffsetSeconds(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitUtcOffsetSeconds(*v)
	}
	return _u
}

// AddExitUtcOffsetSeconds adds value to the "exit_utc_offset_seconds" field.
func (_u *ProxyUpdateOne) AddExitUtcOffsetSeconds(v int) *ProxyUpdateOne {
	_u.mutation.AddExitUtcOffsetSeconds(v)
	return _u
}

// ClearExitUtcOffsetSeconds clears the value of the "exit_utc_offset_seconds" field.
func (_u *ProxyUpdateOne) ClearExitUtcOffsetSeconds() *ProxyUpdateOne {
	_u.mutation.ClearExitUtcOffsetSeconds()
	return _u
}

// SetExitAsn sets the "exit_asn" field.
func (_u *ProxyUpdateOne) SetExitAsn(v string) *ProxyUpdateOne {
	_u.mutation.SetExitAsn(v)
	return _u
}

// SetNillableExitAsn sets the "exit_asn" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitAsn(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitAsn(*v)
	}
	return _u
}

// ClearExitAsn clears the value of the "exit_asn" field.
func (_u *ProxyUpdateOne) ClearExitAsn() *ProxyUpdateOne {
	_u.mutation.ClearExitAsn()
	return _u
}

// SetExitIsp sets the "exit_isp" field.
func (_u *ProxyUpdateOne) SetExitIsp(v string) *ProxyUpdateOne {
	_u.mutation.SetExitIsp(v)
	return _u
}

// SetNillableExitIsp sets the "exit_isp" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitIsp(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitIsp(*v)
	}
	return _u
}

// ClearExitIsp clears the value of the "exit_isp" field.
func (_u *ProxyUpdateOne) ClearExitIsp() *ProxyUpdateOne {
	_u.mutation.ClearExitIsp()
	return _u
}

// SetExitCheckedAt sets the "exit_checked_at" field.
func (_u *ProxyUpdateOne) SetExitCheckedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetExitCheckedAt(v)
	return _u
}

// SetNillableExitCheckedAt sets the "exit_checked_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExitCheckedAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetExitCheckedAt(*v)
	}
	return _u
}

// ClearExitCheckedAt clears the value of the "exit_checked_at" field.
func (_u *ProxyUpdateOne) ClearExitCheckedAt() *ProxyUpdateOne {
	_u.mutation.ClearExitCheckedAt()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *ProxyUpdateOne) AddAccountIDs(ids ...int64) *ProxyUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *ProxyUpdateOne) AddAccounts(v ...*Account) *ProxyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddPrimaryProxyIDs adds the "primary_proxies" edge to the Proxy entity by IDs.
func (_u *ProxyUpdateOne) AddPrimaryProxyIDs(ids ...int64) *ProxyUpdateOne {
	_u.mutation.AddPrimaryProxyIDs(ids...)
	return _u
}

// AddPrimaryProxies adds the "primary_proxies" edges to the Proxy entity.
func (_u *ProxyUpdateOne) AddPrimaryProxies(v ...*Proxy) *ProxyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrimaryProxyIDs(ids...)
}

// SetBackupProxy sets the "backup_proxy" edge to the Proxy entity.
func (_u *ProxyUpdateOne) SetBackupProxy(v *Proxy) *ProxyUpdateOne {
	return _u.SetBackupProxyID(v.ID)
}

// Mutation returns the ProxyMutation object of the builder.
func (_u *ProxyUpdateOne) Mutation() *ProxyMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *ProxyUpdateOne) ClearAccounts() *ProxyUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *ProxyUpdateOne) RemoveAccountIDs(ids ...int64) *ProxyUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *ProxyUpdateOne) RemoveAccounts(v ...*Account) *ProxyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearPrimaryProxies clears all "primary_proxies" edges to the Proxy entity.
func (_u *ProxyUpdateOne) ClearPrimaryProxies() *ProxyUpdateOne {
	_u.mutation.ClearPrimaryProxies()
	return _u
}

// RemovePrimaryProxyIDs removes the "primary_proxies" edge to Proxy entities by IDs.
func (_u *ProxyUpdateOne) RemovePrimaryProxyIDs(ids ...int64) *ProxyUpdateOne {
	_u.mutation.RemovePrimaryProxyIDs(ids...)
	return _u
}

// RemovePrimaryProxies removes "primary_proxies" edges to Proxy entities.
func (_u *ProxyUpdateOne) RemovePrimaryProxies(v ...*Proxy) *ProxyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrimaryProxyIDs(ids...)
}

// ClearBackupProxy clears the "backup_proxy" edge to the Proxy entity.
func (_u *ProxyUpdateOne) ClearBackupProxy() *ProxyUpdateOne {
	_u.mutation.ClearBackupProxy()
	return _u
}

// Where appends a list predicates to the ProxyUpdate builder.
func (_u *ProxyUpdateOne) Where(ps ...predicate.Proxy) *ProxyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyUpdateOne) Select(field string, fields ...string) *ProxyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Proxy entity.
func (_u *ProxyUpdateOne) Save(ctx context.Context) (*Proxy, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUpdateOne) SaveX(ctx context.Context) *Proxy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := proxy.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Proxy.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := proxy.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Proxy.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := proxy.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Proxy.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := proxy.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Proxy.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Proxy.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FallbackMode(); ok {
		if err := proxy.FallbackModeValidator(v); err != nil {
			return &ValidationError{Name: "fallback_mode", err: fmt.Errorf(`ent: validator failed for field "Proxy.fallback_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitIP(); ok {
		if err := proxy.ExitIPValidator(v); err != nil {
			return &ValidationError{Name: "exit_ip", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitCountry(); ok {
		if err := proxy.ExitCountryValidator(v); err != nil {
			return &ValidationError{Name: "exit_country", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitCountryCode(); ok {
		if err := proxy.ExitCountryCodeValidator(v); err != nil {
			return &ValidationError{Name: "exit_country_code", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_country_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitRegion(); ok {
		if err := proxy.ExitRegionValidator(v); err != nil {
			return &ValidationError{Name: "exit_region", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitCity(); ok {
		if err := proxy.ExitCityValidator(v); err != nil {
			return &ValidationError{Name: "exit_city", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitTimezone(); ok {
		if err := proxy.ExitTimezoneValidator(v); err != nil {
			return &ValidationError{Name: "exit_timezone", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitAsn(); ok {
		if err := proxy.ExitAsnValidator(v); err != nil {
			return &ValidationError{Name: "exit_asn", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_asn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExitIsp(); ok {
		if err := proxy.ExitIspValidator(v); err != nil {
			return &ValidationError{Name: "exit_isp", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_isp": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyUpdateOne) sqlSave(ctx context.Context) (_node *Proxy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxy.Table, proxy.Columns, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Proxy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxy.FieldID)
		for _, f := range fields {
			if !proxy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxy.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxy.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxy.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(proxy.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(proxy.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(proxy.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(proxy.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxy.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(proxy.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(proxy.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FallbackMode(); ok {
		_spec.SetField(proxy.FieldFallbackMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiryWarnDays(); ok {
		_spec.SetField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpiryWarnDays(); ok {
		_spec.AddField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExitIP(); ok {
		_spec.SetField(proxy.FieldExitIP, field.TypeString, value)
	}
	if _u.mutation.ExitIPCleared() {
		_spec.ClearField(proxy.FieldExitIP, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCountry(); ok {
		_spec.SetField(proxy.FieldExitCountry, field.TypeString, value)
	}
	if _u.mutation.ExitCountryCleared() {
		_spec.ClearField(proxy.FieldExitCountry, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCountryCode(); ok {
		_spec.SetField(proxy.FieldExitCountryCode, field.TypeString, value)
	}
	if _u.mutation.ExitCountryCodeCleared() {
		_spec.ClearField(proxy.FieldExitCountryCode, field.TypeString)
	}
	if value, ok := _u.mutation.ExitRegion(); ok {
		_spec.SetField(proxy.FieldExitRegion, field.TypeString, value)
	}
	if _u.mutation.ExitRegionCleared() {
		_spec.ClearField(proxy.FieldExitRegion, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCity(); ok {
		_spec.SetField(proxy.FieldExitCity, field.TypeString, value)
	}
	if _u.mutation.ExitCityCleared() {
		_spec.ClearField(proxy.FieldExitCity, field.TypeString)
	}
	if value, ok := _u.mutation.ExitTimezone(); ok {
		_spec.SetField(proxy.FieldExitTimezone, field.TypeString, value)
	}
	if _u.mutation.ExitTimezoneCleared() {
		_spec.ClearField(proxy.FieldExitTimezone, field.TypeString)
	}
	if value, ok := _u.mutation.ExitUtcOffsetSeconds(); ok {
		_spec.SetField(proxy.FieldExitUtcOffsetSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExitUtcOffsetSeconds(); ok {
		_spec.AddField(proxy.FieldExitUtcOffsetSeconds, field.TypeInt, value)
	}
	if _u.mutation.ExitUtcOffsetSecondsCleared() {
		_spec.ClearField(proxy.FieldExitUtcOffsetSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.ExitAsn(); ok {
		_spec.SetField(proxy.FieldExitAsn, field.TypeString, value)
	}
	if _u.mutation.ExitAsnCleared() {
		_spec.ClearField(proxy.FieldExitAsn, field.TypeString)
	}
	if value, ok := _u.mutation.ExitIsp(); ok {
		_spec.SetField(proxy.FieldExitIsp, field.TypeString, value)
	}
	if _u.mutation.ExitIspCleared() {
		_spec.ClearField(proxy.FieldExitIsp, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCheckedAt(); ok {
		_spec.SetField(proxy.FieldExitCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.ExitCheckedAtCleared() {
		_spec.ClearField(proxy.FieldExitCheckedAt, field.TypeTime)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrimaryProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.PrimaryProxiesTable,
			Columns: []string{proxy.PrimaryProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrimaryProxiesIDs(); len(nodes) > 0 && !_u.mutation.PrimaryProxiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.PrimaryProxiesTable,
			Columns: []string{proxy.PrimaryProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrimaryProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.PrimaryProxiesTable,
			Columns: []string{proxy.PrimaryProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BackupProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BackupProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Proxy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
