// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jk-zhang-meta/berth/ent/account"
	"github.com/jk-zhang-meta/berth/ent/proxy"
)

// ProxyCreate is the builder for creating a Proxy entity.
type ProxyCreate struct {
	config
	mutation *ProxyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyCreate) SetCreatedAt(v time.Time) *ProxyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableCreatedAt(v *time.Time) *ProxyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyCreate) SetUpdatedAt(v time.Time) *ProxyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableUpdatedAt(v *time.Time) *ProxyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProxyCreate) SetDeletedAt(v time.Time) *ProxyCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableDeletedAt(v *time.Time) *ProxyCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProxyCreate) SetName(v string) *ProxyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *ProxyCreate) SetProtocol(v string) *ProxyCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetHost sets the "host" field.
func (_c *ProxyCreate) SetHost(v string) *ProxyCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetPort sets the "port" field.
func (_c *ProxyCreate) SetPort(v int) *ProxyCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *ProxyCreate) SetUsername(v string) *ProxyCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableUsername(v *string) *ProxyCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *ProxyCreate) SetPassword(v string) *ProxyCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *ProxyCreate) SetNillablePassword(v *string) *ProxyCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProxyCreate) SetStatus(v string) *ProxyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableStatus(v *string) *ProxyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ProxyCreate) SetExpiresAt(v time.Time) *ProxyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExpiresAt(v *time.Time) *ProxyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetFallbackMode sets the "fallback_mode" field.
func (_c *ProxyCreate) SetFallbackMode(v string) *ProxyCreate {
	_c.mutation.SetFallbackMode(v)
	return _c
}

// SetNillableFallbackMode sets the "fallback_mode" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableFallbackMode(v *string) *ProxyCreate {
	if v != nil {
		_c.SetFallbackMode(*v)
	}
	return _c
}

// SetBackupProxyID sets the "backup_proxy_id" field.
func (_c *ProxyCreate) SetBackupProxyID(v int64) *ProxyCreate {
	_c.mutation.SetBackupProxyID(v)
	return _c
}

// SetNillableBackupProxyID sets the "backup_proxy_id" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableBackupProxyID(v *int64) *ProxyCreate {
	if v != nil {
		_c.SetBackupProxyID(*v)
	}
	return _c
}

// SetExpiryWarnDays sets the "expiry_warn_days" field.
func (_c *ProxyCreate) SetExpiryWarnDays(v int) *ProxyCreate {
	_c.mutation.SetExpiryWarnDays(v)
	return _c
}

// SetNillableExpiryWarnDays sets the "expiry_warn_days" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExpiryWarnDays(v *int) *ProxyCreate {
	if v != nil {
		_c.SetExpiryWarnDays(*v)
	}
	return _c
}

// SetMaxAccounts sets the "max_accounts" field.
func (_c *ProxyCreate) SetMaxAccounts(v int) *ProxyCreate {
	_c.mutation.SetMaxAccounts(v)
	return _c
}

// SetNillableMaxAccounts sets the "max_accounts" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableMaxAccounts(v *int) *ProxyCreate {
	if v != nil {
		_c.SetMaxAccounts(*v)
	}
	return _c
}

// SetMaxRpm sets the "max_rpm" field.
func (_c *ProxyCreate) SetMaxRpm(v int) *ProxyCreate {
	_c.mutation.SetMaxRpm(v)
	return _c
}

// SetNillableMaxRpm sets the "max_rpm" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableMaxRpm(v *int) *ProxyCreate {
	if v != nil {
		_c.SetMaxRpm(*v)
	}
	return _c
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (_c *ProxyCreate) SetMaxConcurrency(v int) *ProxyCreate {
	_c.mutation.SetMaxConcurrency(v)
	return _c
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableMaxConcurrency(v *int) *ProxyCreate {
	if v != nil {
		_c.SetMaxConcurrency(*v)
	}
	return _c
}

// SetExitIP sets the "exit_ip" field.
func (_c *ProxyCreate) SetExitIP(v string) *ProxyCreate {
	_c.mutation.SetExitIP(v)
	return _c
}

// SetNillableExitIP sets the "exit_ip" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitIP(v *string) *ProxyCreate {
	if v != nil {
		_c.SetExitIP(*v)
	}
	return _c
}

// SetExitCountry sets the "exit_country" field.
func (_c *ProxyCreate) SetExitCountry(v string) *ProxyCreate {
	_c.mutation.SetExitCountry(v)
	return _c
}

// SetNillableExitCountry sets the "exit_country" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitCountry(v *string) *ProxyCreate {
	if v != nil {
		_c.SetExitCountry(*v)
	}
	return _c
}

// SetExitCountryCode sets the "exit_country_code" field.
func (_c *ProxyCreate) SetExitCountryCode(v string) *ProxyCreate {
	_c.mutation.SetExitCountryCode(v)
	return _c
}

// SetNillableExitCountryCode sets the "exit_country_code" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitCountryCode(v *string) *ProxyCreate {
	if v != nil {
		_c.SetExitCountryCode(*v)
	}
	return _c
}

// SetExitRegion sets the "exit_region" field.
func (_c *ProxyCreate) SetExitRegion(v string) *ProxyCreate {
	_c.mutation.SetExitRegion(v)
	return _c
}

// SetNillableExitRegion sets the "exit_region" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitRegion(v *string) *ProxyCreate {
	if v != nil {
		_c.SetExitRegion(*v)
	}
	return _c
}

// SetExitCity sets the "exit_city" field.
func (_c *ProxyCreate) SetExitCity(v string) *ProxyCreate {
	_c.mutation.SetExitCity(v)
	return _c
}

// SetNillableExitCity sets the "exit_city" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitCity(v *string) *ProxyCreate {
	if v != nil {
		_c.SetExitCity(*v)
	}
	return _c
}

// SetExitTimezone sets the "exit_timezone" field.
func (_c *ProxyCreate) SetExitTimezone(v string) *ProxyCreate {
	_c.mutation.SetExitTimezone(v)
	return _c
}

// SetNillableExitTimezone sets the "exit_timezone" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitTimezone(v *string) *ProxyCreate {
	if v != nil {
		_c.SetExitTimezone(*v)
	}
	return _c
}

// SetExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field.
func (_c *ProxyCreate) SetExitUtcOffsetSeconds(v int) *ProxyCreate {
	_c.mutation.SetExitUtcOffsetSeconds(v)
	return _c
}

// SetNillableExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitUtcOffsetSeconds(v *int) *ProxyCreate {
	if v != nil {
		_c.SetExitUtcOffsetSeconds(*v)
	}
	return _c
}

// SetExitAsn sets the "exit_asn" field.
func (_c *ProxyCreate) SetExitAsn(v string) *ProxyCreate {
	_c.mutation.SetExitAsn(v)
	return _c
}

// SetNillableExitAsn sets the "exit_asn" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitAsn(v *string) *ProxyCreate {
	if v != nil {
		_c.SetExitAsn(*v)
	}
	return _c
}

// SetExitIsp sets the "exit_isp" field.
func (_c *ProxyCreate) SetExitIsp(v string) *ProxyCreate {
	_c.mutation.SetExitIsp(v)
	return _c
}

// SetNillableExitIsp sets the "exit_isp" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitIsp(v *string) *ProxyCreate {
	if v != nil {
		_c.SetExitIsp(*v)
	}
	return _c
}

// SetExitCheckedAt sets the "exit_checked_at" field.
func (_c *ProxyCreate) SetExitCheckedAt(v time.Time) *ProxyCreate {
	_c.mutation.SetExitCheckedAt(v)
	return _c
}

// SetNillableExitCheckedAt sets the "exit_checked_at" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableExitCheckedAt(v *time.Time) *ProxyCreate {
	if v != nil {
		_c.SetExitCheckedAt(*v)
	}
	return _c
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *ProxyCreate) AddAccountIDs(ids ...int64) *ProxyCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *ProxyCreate) AddAccounts(v ...*Account) *ProxyCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// AddPrimaryProxyIDs adds the "primary_proxies" edge to the Proxy entity by IDs.
func (_c *ProxyCreate) AddPrimaryProxyIDs(ids ...int64) *ProxyCreate {
	_c.mutation.AddPrimaryProxyIDs(ids...)
	return _c
}

// AddPrimaryProxies adds the "primary_proxies" edges to the Proxy entity.
func (_c *ProxyCreate) AddPrimaryProxies(v ...*Proxy) *ProxyCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPrimaryProxyIDs(ids...)
}

// SetBackupProxy sets the "backup_proxy" edge to the Proxy entity.
func (_c *ProxyCreate) SetBackupProxy(v *Proxy) *ProxyCreate {
	return _c.SetBackupProxyID(v.ID)
}

// Mutation returns the ProxyMutation object of the builder.
func (_c *ProxyCreate) Mutation() *ProxyMutation {
	return _c.mutation
}

// Save creates the Proxy in the database.
func (_c *ProxyCreate) Save(ctx context.Context) (*Proxy, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyCreate) SaveX(ctx context.Context) *Proxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if proxy.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxy.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := proxy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if proxy.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxy.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := proxy.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.FallbackMode(); !ok {
		v := proxy.DefaultFallbackMode
		_c.mutation.SetFallbackMode(v)
	}
	if _, ok := _c.mutation.ExpiryWarnDays(); !ok {
		v := proxy.DefaultExpiryWarnDays
		_c.mutation.SetExpiryWarnDays(v)
	}
	if _, ok := _c.mutation.MaxAccounts(); !ok {
		v := proxy.DefaultMaxAccounts
		_c.mutation.SetMaxAccounts(v)
	}
	if _, ok := _c.mutation.MaxRpm(); !ok {
		v := proxy.DefaultMaxRpm
		_c.mutation.SetMaxRpm(v)
	}
	if _, ok := _c.mutation.MaxConcurrency(); !ok {
		v := proxy.DefaultMaxConcurrency
		_c.mutation.SetMaxConcurrency(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Proxy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Proxy.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Proxy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "Proxy.protocol"`)}
	}
	if v, ok := _c.mutation.Protocol(); ok {
		if err := proxy.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Proxy.protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Proxy.host"`)}
	}
	if v, ok := _c.mutation.Host(); ok {
		if err := proxy.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Proxy.host": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "Proxy.port"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := proxy.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Proxy.username": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := proxy.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Proxy.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Proxy.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := proxy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Proxy.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FallbackMode(); !ok {
		return &ValidationError{Name: "fallback_mode", err: errors.New(`ent: missing required field "Proxy.fallback_mode"`)}
	}
	if v, ok := _c.mutation.FallbackMode(); ok {
		if err := proxy.FallbackModeValidator(v); err != nil {
			return &ValidationError{Name: "fallback_mode", err: fmt.Errorf(`ent: validator failed for field "Proxy.fallback_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiryWarnDays(); !ok {
		return &ValidationError{Name: "expiry_warn_days", err: errors.New(`ent: missing required field "Proxy.expiry_warn_days"`)}
	}
	if _, ok := _c.mutation.MaxAccounts(); !ok {
		return &ValidationError{Name: "max_accounts", err: errors.New(`ent: missing required field "Proxy.max_accounts"`)}
	}
	if v, ok := _c.mutation.MaxAccounts(); ok {
		if err := proxy.MaxAccountsValidator(v); err != nil {
			return &ValidationError{Name: "max_accounts", err: fmt.Errorf(`ent: validator failed for field "Proxy.max_accounts": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxRpm(); !ok {
		return &ValidationError{Name: "max_rpm", err: errors.New(`ent: missing required field "Proxy.max_rpm"`)}
	}
	if v, ok := _c.mutation.MaxRpm(); ok {
		if err := proxy.MaxRpmValidator(v); err != nil {
			return &ValidationError{Name: "max_rpm", err: fmt.Errorf(`ent: validator failed for field "Proxy.max_rpm": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxConcurrency(); !ok {
		return &ValidationError{Name: "max_concurrency", err: errors.New(`ent: missing required field "Proxy.max_concurrency"`)}
	}
	if v, ok := _c.mutation.MaxConcurrency(); ok {
		if err := proxy.MaxConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "max_concurrency", err: fmt.Errorf(`ent: validator failed for field "Proxy.max_concurrency": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitIP(); ok {
		if err := proxy.ExitIPValidator(v); err != nil {
			return &ValidationError{Name: "exit_ip", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitCountry(); ok {
		if err := proxy.ExitCountryValidator(v); err != nil {
			return &ValidationError{Name: "exit_country", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_country": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitCountryCode(); ok {
		if err := proxy.ExitCountryCodeValidator(v); err != nil {
			return &ValidationError{Name: "exit_country_code", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_country_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitRegion(); ok {
		if err := proxy.ExitRegionValidator(v); err != nil {
			return &ValidationError{Name: "exit_region", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_region": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitCity(); ok {
		if err := proxy.ExitCityValidator(v); err != nil {
			return &ValidationError{Name: "exit_city", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_city": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitTimezone(); ok {
		if err := proxy.ExitTimezoneValidator(v); err != nil {
			return &ValidationError{Name: "exit_timezone", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_timezone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitAsn(); ok {
		if err := proxy.ExitAsnValidator(v); err != nil {
			return &ValidationError{Name: "exit_asn", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_asn": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExitIsp(); ok {
		if err := proxy.ExitIspValidator(v); err != nil {
			return &ValidationError{Name: "exit_isp", err: fmt.Errorf(`ent: validator failed for field "Proxy.exit_isp": %w`, err)}
		}
	}
	return nil
}

func (_c *ProxyCreate) sqlSave(ctx context.Context) (*Proxy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyCreate) createSpec() (*Proxy, *sqlgraph.CreateSpec) {
	var (
		_node = &Proxy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxy.Table, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(proxy.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(proxy.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(proxy.FieldUsername, field.TypeString, value)
		_node.Username = &value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(proxy.FieldPassword, field.TypeString, value)
		_node.Password = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(proxy.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(proxy.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.FallbackMode(); ok {
		_spec.SetField(proxy.FieldFallbackMode, field.TypeString, value)
		_node.FallbackMode = value
	}
	if value, ok := _c.mutation.ExpiryWarnDays(); ok {
		_spec.SetField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
		_node.ExpiryWarnDays = value
	}
	if value, ok := _c.mutation.MaxAccounts(); ok {
		_spec.SetField(proxy.FieldMaxAccounts, field.TypeInt, value)
		_node.MaxAccounts = value
	}
	if value, ok := _c.mutation.MaxRpm(); ok {
		_spec.SetField(proxy.FieldMaxRpm, field.TypeInt, value)
		_node.MaxRpm = value
	}
	if value, ok := _c.mutation.MaxConcurrency(); ok {
		_spec.SetField(proxy.FieldMaxConcurrency, field.TypeInt, value)
		_node.MaxConcurrency = value
	}
	if value, ok := _c.mutation.ExitIP(); ok {
		_spec.SetField(proxy.FieldExitIP, field.TypeString, value)
		_node.ExitIP = &value
	}
	if value, ok := _c.mutation.ExitCountry(); ok {
		_spec.SetField(proxy.FieldExitCountry, field.TypeString, value)
		_node.ExitCountry = &value
	}
	if value, ok := _c.mutation.ExitCountryCode(); ok {
		_spec.SetField(proxy.FieldExitCountryCode, field.TypeString, value)
		_node.ExitCountryCode = &value
	}
	if value, ok := _c.mutation.ExitRegion(); ok {
		_spec.SetField(proxy.FieldExitRegion, field.TypeString, value)
		_node.ExitRegion = &value
	}
	if value, ok := _c.mutation.ExitCity(); ok {
		_spec.SetField(proxy.FieldExitCity, field.TypeString, value)
		_node.ExitCity = &value
	}
	if value, ok := _c.mutation.ExitTimezone(); ok {
		_spec.SetField(proxy.FieldExitTimezone, field.TypeString, value)
		_node.ExitTimezone = &value
	}
	if value, ok := _c.mutation.ExitUtcOffsetSeconds(); ok {
		_spec.SetField(proxy.FieldExitUtcOffsetSeconds, field.TypeInt, value)
		_node.ExitUtcOffsetSeconds = &value
	}
	if value, ok := _c.mutation.ExitAsn(); ok {
		_spec.SetField(proxy.FieldExitAsn, field.TypeString, value)
		_node.ExitAsn = &value
	}
	if value, ok := _c.mutation.ExitIsp(); ok {
		_spec.SetField(proxy.FieldExitIsp, field.TypeString, value)
		_node.ExitIsp = &value
	}
	if value, ok := _c.mutation.ExitCheckedAt(); ok {
		_spec.SetField(proxy.FieldExitCheckedAt, field.TypeTime, value)
		_node.ExitCheckedAt = &value
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PrimaryProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.PrimaryProxiesTable,
			Columns: []string{proxy.PrimaryProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BackupProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BackupProxyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Proxy.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyCreate) OnConflict(opts ...sql.ConflictOption) *ProxyUpsertOne {
	_c.conflict = opts
	return &ProxyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Proxy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyCreate) OnConflictColumns(columns ...string) *ProxyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyUpsertOne{
		create: _c,
	}
}

type (
	// ProxyUpsertOne is the builder for "upsert"-ing
	//  one Proxy node.
	ProxyUpsertOne struct {
		create *ProxyCreate
	}

	// ProxyUpsert is the "OnConflict" setter.
	ProxyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyUpsert) SetUpdatedAt(v time.Time) *ProxyUpsert {
	u.Set(proxy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateUpdatedAt() *ProxyUpsert {
	u.SetExcluded(proxy.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxyUpsert) SetDeletedAt(v time.Time) *ProxyUpsert {
	u.Set(proxy.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateDeletedAt() *ProxyUpsert {
	u.SetExcluded(proxy.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxyUpsert) ClearDeletedAt() *ProxyUpsert {
	u.SetNull(proxy.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *ProxyUpsert) SetName(v string) *ProxyUpsert {
	u.Set(proxy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateName() *ProxyUpsert {
	u.SetExcluded(proxy.FieldName)
	return u
}

// SetProtocol sets the "protocol" field.
func (u *ProxyUpsert) SetProtocol(v string) *ProxyUpsert {
	u.Set(proxy.FieldProtocol, v)
	return u
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateProtocol() *ProxyUpsert {
	u.SetExcluded(proxy.FieldProtocol)
	return u
}

// SetHost sets the "host" field.
func (u *ProxyUpsert) SetHost(v string) *ProxyUpsert {
	u.Set(proxy.FieldHost, v)
	return u
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateHost() *ProxyUpsert {
	u.SetExcluded(proxy.FieldHost)
	return u
}

// SetPort sets the "port" field.
func (u *ProxyUpsert) SetPort(v int) *ProxyUpsert {
	u.Set(proxy.FieldPort, v)
	return u
}

// UpdatePort sets the "port" field to the value that was provided on create.
func (u *ProxyUpsert) UpdatePort() *ProxyUpsert {
	u.SetExcluded(proxy.FieldPort)
	return u
}

// AddPort adds v to the "port" field.
func (u *ProxyUpsert) AddPort(v int) *ProxyUpsert {
	u.Add(proxy.FieldPort, v)
	return u
}

// SetUsername sets the "username" field.
func (u *ProxyUpsert) SetUsername(v string) *ProxyUpsert {
	u.Set(proxy.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateUsername() *ProxyUpsert {
	u.SetExcluded(proxy.FieldUsername)
	return u
}

// ClearUsername clears the value of the "username" field.
func (u *ProxyUpsert) ClearUsername() *ProxyUpsert {
	u.SetNull(proxy.FieldUsername)
	return u
}

// SetPassword sets the "password" field.
func (u *ProxyUpsert) SetPassword(v string) *ProxyUpsert {
	u.Set(proxy.FieldPassword, v)
	return u
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *ProxyUpsert) UpdatePassword() *ProxyUpsert {
	u.SetExcluded(proxy.FieldPassword)
	return u
}

// ClearPassword clears the value of the "password" field.
func (u *ProxyUpsert) ClearPassword() *ProxyUpsert {
	u.SetNull(proxy.FieldPassword)
	return u
}

// SetStatus sets the "status" field.
func (u *ProxyUpsert) SetStatus(v string) *ProxyUpsert {
	u.Set(proxy.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateStatus() *ProxyUpsert {
	u.SetExcluded(proxy.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyUpsert) SetExpiresAt(v time.Time) *ProxyUpsert {
	u.Set(proxy.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExpiresAt() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyUpsert) ClearExpiresAt() *ProxyUpsert {
	u.SetNull(proxy.FieldExpiresAt)
	return u
}

// SetFallbackMode sets the "fallback_mode" field.
func (u *ProxyUpsert) SetFallbackMode(v string) *ProxyUpsert {
	u.Set(proxy.FieldFallbackMode, v)
	return u
}

// UpdateFallbackMode sets the "fallback_mode" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateFallbackMode() *ProxyUpsert {
	u.SetExcluded(proxy.FieldFallbackMode)
	return u
}

// SetBackupProxyID sets the "backup_proxy_id" field.
func (u *ProxyUpsert) SetBackupProxyID(v int64) *ProxyUpsert {
	u.Set(proxy.FieldBackupProxyID, v)
	return u
}

// UpdateBackupProxyID sets the "backup_proxy_id" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateBackupProxyID() *ProxyUpsert {
	u.SetExcluded(proxy.FieldBackupProxyID)
	return u
}

// ClearBackupProxyID clears the value of the "backup_proxy_id" field.
func (u *ProxyUpsert) ClearBackupProxyID() *ProxyUpsert {
	u.SetNull(proxy.FieldBackupProxyID)
	return u
}

// SetExpiryWarnDays sets the "expiry_warn_days" field.
func (u *ProxyUpsert) SetExpiryWarnDays(v int) *ProxyUpsert {
	u.Set(proxy.FieldExpiryWarnDays, v)
	return u
}

// UpdateExpiryWarnDays sets the "expiry_warn_days" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExpiryWarnDays() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExpiryWarnDays)
	return u
}

// AddExpiryWarnDays adds v to the "expiry_warn_days" field.
func (u *ProxyUpsert) AddExpiryWarnDays(v int) *ProxyUpsert {
	u.Add(proxy.FieldExpiryWarnDays, v)
	return u
}

// SetMaxAccounts sets the "max_accounts" field.
func (u *ProxyUpsert) SetMaxAccounts(v int) *ProxyUpsert {
	u.Set(proxy.FieldMaxAccounts, v)
	return u
}

// UpdateMaxAccounts sets the "max_accounts" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateMaxAccounts() *ProxyUpsert {
	u.SetExcluded(proxy.FieldMaxAccounts)
	return u
}

// AddMaxAccounts adds v to the "max_accounts" field.
func (u *ProxyUpsert) AddMaxAccounts(v int) *ProxyUpsert {
	u.Add(proxy.FieldMaxAccounts, v)
	return u
}

// SetMaxRpm sets the "max_rpm" field.
func (u *ProxyUpsert) SetMaxRpm(v int) *ProxyUpsert {
	u.Set(proxy.FieldMaxRpm, v)
	return u
}

// UpdateMaxRpm sets the "max_rpm" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateMaxRpm() *ProxyUpsert {
	u.SetExcluded(proxy.FieldMaxRpm)
	return u
}

// AddMaxRpm adds v to the "max_rpm" field.
func (u *ProxyUpsert) AddMaxRpm(v int) *ProxyUpsert {
	u.Add(proxy.FieldMaxRpm, v)
	return u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *ProxyUpsert) SetMaxConcurrency(v int) *ProxyUpsert {
	u.Set(proxy.FieldMaxConcurrency, v)
	return u
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateMaxConcurrency() *ProxyUpsert {
	u.SetExcluded(proxy.FieldMaxConcurrency)
	return u
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *ProxyUpsert) AddMaxConcurrency(v int) *ProxyUpsert {
	u.Add(proxy.FieldMaxConcurrency, v)
	return u
}

// SetExitIP sets the "exit_ip" field.
func (u *ProxyUpsert) SetExitIP(v string) *ProxyUpsert {
	u.Set(proxy.FieldExitIP, v)
	return u
}

// UpdateExitIP sets the "exit_ip" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitIP() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitIP)
	return u
}

// ClearExitIP clears the value of the "exit_ip" field.
func (u *ProxyUpsert) ClearExitIP() *ProxyUpsert {
	u.SetNull(proxy.FieldExitIP)
	return u
}

// SetExitCountry sets the "exit_country" field.
func (u *ProxyUpsert) SetExitCountry(v string) *ProxyUpsert {
	u.Set(proxy.FieldExitCountry, v)
	return u
}

// UpdateExitCountry sets the "exit_country" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitCountry() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitCountry)
	return u
}

// ClearExitCountry clears the value of the "exit_country" field.
func (u *ProxyUpsert) ClearExitCountry() *ProxyUpsert {
	u.SetNull(proxy.FieldExitCountry)
	return u
}

// SetExitCountryCode sets the "exit_country_code" field.
func (u *ProxyUpsert) SetExitCountryCode(v string) *ProxyUpsert {
	u.Set(proxy.FieldExitCountryCode, v)
	return u
}

// UpdateExitCountryCode sets the "exit_country_code" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitCountryCode() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitCountryCode)
	return u
}

// ClearExitCountryCode clears the value of the "exit_country_code" field.
func (u *ProxyUpsert) ClearExitCountryCode() *ProxyUpsert {
	u.SetNull(proxy.FieldExitCountryCode)
	return u
}

// SetExitRegion sets the "exit_region" field.
func (u *ProxyUpsert) SetExitRegion(v string) *ProxyUpsert {
	u.Set(proxy.FieldExitRegion, v)
	return u
}

// UpdateExitRegion sets the "exit_region" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitRegion() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitRegion)
	return u
}

// ClearExitRegion clears the value of the "exit_region" field.
func (u *ProxyUpsert) ClearExitRegion() *ProxyUpsert {
	u.SetNull(proxy.FieldExitRegion)
	return u
}

// SetExitCity sets the "exit_city" field.
func (u *ProxyUpsert) SetExitCity(v string) *ProxyUpsert {
	u.Set(proxy.FieldExitCity, v)
	return u
}

// UpdateExitCity sets the "exit_city" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitCity() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitCity)
	return u
}

// ClearExitCity clears the value of the "exit_city" field.
func (u *ProxyUpsert) ClearExitCity() *ProxyUpsert {
	u.SetNull(proxy.FieldExitCity)
	return u
}

// SetExitTimezone sets the "exit_timezone" field.
func (u *ProxyUpsert) SetExitTimezone(v string) *ProxyUpsert {
	u.Set(proxy.FieldExitTimezone, v)
	return u
}

// UpdateExitTimezone sets the "exit_timezone" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitTimezone() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitTimezone)
	return u
}

// ClearExitTimezone clears the value of the "exit_timezone" field.
func (u *ProxyUpsert) ClearExitTimezone() *ProxyUpsert {
	u.SetNull(proxy.FieldExitTimezone)
	return u
}

// SetExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field.
func (u *ProxyUpsert) SetExitUtcOffsetSeconds(v int) *ProxyUpsert {
	u.Set(proxy.FieldExitUtcOffsetSeconds, v)
	return u
}

// UpdateExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitUtcOffsetSeconds() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitUtcOffsetSeconds)
	return u
}

// AddExitUtcOffsetSeconds adds v to the "exit_utc_offset_seconds" field.
func (u *ProxyUpsert) AddExitUtcOffsetSeconds(v int) *ProxyUpsert {
	u.Add(proxy.FieldExitUtcOffsetSeconds, v)
	return u
}

// ClearExitUtcOffsetSeconds clears the value of the "exit_utc_offset_seconds" field.
func (u *ProxyUpsert) ClearExitUtcOffsetSeconds() *ProxyUpsert {
	u.SetNull(proxy.FieldExitUtcOffsetSeconds)
	return u
}

// SetExitAsn sets the "exit_asn" field.
func (u *ProxyUpsert) SetExitAsn(v string) *ProxyUpsert {
	u.Set(proxy.FieldExitAsn, v)
	return u
}

// UpdateExitAsn sets the "exit_asn" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitAsn() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitAsn)
	return u
}

// ClearExitAsn clears the value of the "exit_asn" field.
func (u *ProxyUpsert) ClearExitAsn() *ProxyUpsert {
	u.SetNull(proxy.FieldExitAsn)
	return u
}

// SetExitIsp sets the "exit_isp" field.
func (u *ProxyUpsert) SetExitIsp(v string) *ProxyUpsert {
	u.Set(proxy.FieldExitIsp, v)
	return u
}

// UpdateExitIsp sets the "exit_isp" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitIsp() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitIsp)
	return u
}

// ClearExitIsp clears the value of the "exit_isp" field.
func (u *ProxyUpsert) ClearExitIsp() *ProxyUpsert {
	u.SetNull(proxy.FieldExitIsp)
	return u
}

// SetExitCheckedAt sets the "exit_checked_at" field.
func (u *ProxyUpsert) SetExitCheckedAt(v time.Time) *ProxyUpsert {
	u.Set(proxy.FieldExitCheckedAt, v)
	return u
}

// UpdateExitCheckedAt sets the "exit_checked_at" field to the value that was provided on create.
func (u *ProxyUpsert) UpdateExitCheckedAt() *ProxyUpsert {
	u.SetExcluded(proxy.FieldExitCheckedAt)
	return u
}

// ClearExitCheckedAt clears the value of the "exit_checked_at" field.
func (u *ProxyUpsert) ClearExitCheckedAt() *ProxyUpsert {
	u.SetNull(proxy.FieldExitCheckedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Proxy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyUpsertOne) UpdateNewValues() *ProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Proxy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyUpsertOne) Ignore() *ProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyUpsertOne) DoNothing() *ProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyCreate.OnConflict
// documentation for more info.
func (u *ProxyUpsertOne) Update(set func(*ProxyUpsert)) *ProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyUpsertOne) SetUpdatedAt(v time.Time) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateUpdatedAt() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxyUpsertOne) SetDeletedAt(v time.Time) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateDeletedAt() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxyUpsertOne) ClearDeletedAt() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxyUpsertOne) SetName(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateName() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateName()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ProxyUpsertOne) SetProtocol(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateProtocol() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateProtocol()
	})
}

// SetHost sets the "host" field.
func (u *ProxyUpsertOne) SetHost(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetHost(v)
	})
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateHost() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateHost()
	})
}

// SetPort sets the "port" field.
func (u *ProxyUpsertOne) SetPort(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetPort(v)
	})
}

// AddPort adds v to the "port" field.
func (u *ProxyUpsertOne) AddPort(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.AddPort(v)
	})
}

// UpdatePort sets the "port" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdatePort() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdatePort()
	})
}

// SetUsername sets the "username" field.
func (u *ProxyUpsertOne) SetUsername(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateUsername() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *ProxyUpsertOne) ClearUsername() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearUsername()
	})
}

// SetPassword sets the "password" field.
func (u *ProxyUpsertOne) SetPassword(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdatePassword() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdatePassword()
	})
}

// ClearPassword clears the value of the "password" field.
func (u *ProxyUpsertOne) ClearPassword() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearPassword()
	})
}

// SetStatus sets the "status" field.
func (u *ProxyUpsertOne) SetStatus(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateStatus() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyUpsertOne) SetExpiresAt(v time.Time) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExpiresAt() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyUpsertOne) ClearExpiresAt() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExpiresAt()
	})
}

// SetFallbackMode sets the "fallback_mode" field.
func (u *ProxyUpsertOne) SetFallbackMode(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetFallbackMode(v)
	})
}

// UpdateFallbackMode sets the "fallback_mode" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateFallbackMode() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateFallbackMode()
	})
}

// SetBackupProxyID sets the "backup_proxy_id" field.
func (u *ProxyUpsertOne) SetBackupProxyID(v int64) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetBackupProxyID(v)
	})
}

// UpdateBackupProxyID sets the "backup_proxy_id" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateBackupProxyID() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateBackupProxyID()
	})
}

// ClearBackupProxyID clears the value of the "backup_proxy_id" field.
func (u *ProxyUpsertOne) ClearBackupProxyID() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearBackupProxyID()
	})
}

// SetExpiryWarnDays sets the "expiry_warn_days" field.
func (u *ProxyUpsertOne) SetExpiryWarnDays(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExpiryWarnDays(v)
	})
}

// AddExpiryWarnDays adds v to the "expiry_warn_days" field.
func (u *ProxyUpsertOne) AddExpiryWarnDays(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.AddExpiryWarnDays(v)
	})
}

// UpdateExpiryWarnDays sets the "expiry_warn_days" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExpiryWarnDays() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExpiryWarnDays()
	})
}

// SetMaxAccounts sets the "max_accounts" field.
func (u *ProxyUpsertOne) SetMaxAccounts(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetMaxAccounts(v)
	})
}

// AddMaxAccounts adds v to the "max_accounts" field.
func (u *ProxyUpsertOne) AddMaxAccounts(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.AddMaxAccounts(v)
	})
}

// UpdateMaxAccounts sets the "max_accounts" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateMaxAccounts() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateMaxAccounts()
	})
}

// SetMaxRpm sets the "max_rpm" field.
func (u *ProxyUpsertOne) SetMaxRpm(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetMaxRpm(v)
	})
}

// AddMaxRpm adds v to the "max_rpm" field.
func (u *ProxyUpsertOne) AddMaxRpm(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.AddMaxRpm(v)
	})
}

// UpdateMaxRpm sets the "max_rpm" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateMaxRpm() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateMaxRpm()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *ProxyUpsertOne) SetMaxConcurrency(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *ProxyUpsertOne) AddMaxConcurrency(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateMaxConcurrency() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// SetExitIP sets the "exit_ip" field.
func (u *ProxyUpsertOne) SetExitIP(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitIP(v)
	})
}

// UpdateExitIP sets the "exit_ip" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitIP() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitIP()
	})
}

// ClearExitIP clears the value of the "exit_ip" field.
func (u *ProxyUpsertOne) ClearExitIP() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitIP()
	})
}

// SetExitCountry sets the "exit_country" field.
func (u *ProxyUpsertOne) SetExitCountry(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitCountry(v)
	})
}

// UpdateExitCountry sets the "exit_country" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitCountry() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitCountry()
	})
}

// ClearExitCountry clears the value of the "exit_country" field.
func (u *ProxyUpsertOne) ClearExitCountry() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitCountry()
	})
}

// SetExitCountryCode sets the "exit_country_code" field.
func (u *ProxyUpsertOne) SetExitCountryCode(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitCountryCode(v)
	})
}

// UpdateExitCountryCode sets the "exit_country_code" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitCountryCode() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitCountryCode()
	})
}

// ClearExitCountryCode clears the value of the "exit_country_code" field.
func (u *ProxyUpsertOne) ClearExitCountryCode() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitCountryCode()
	})
}

// SetExitRegion sets the "exit_region" field.
func (u *ProxyUpsertOne) SetExitRegion(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitRegion(v)
	})
}

// UpdateExitRegion sets the "exit_region" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitRegion() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitRegion()
	})
}

// ClearExitRegion clears the value of the "exit_region" field.
func (u *ProxyUpsertOne) ClearExitRegion() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitRegion()
	})
}

// SetExitCity sets the "exit_city" field.
func (u *ProxyUpsertOne) SetExitCity(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitCity(v)
	})
}

// UpdateExitCity sets the "exit_city" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitCity() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitCity()
	})
}

// ClearExitCity clears the value of the "exit_city" field.
func (u *ProxyUpsertOne) ClearExitCity() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitCity()
	})
}

// SetExitTimezone sets the "exit_timezone" field.
func (u *ProxyUpsertOne) SetExitTimezone(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitTimezone(v)
	})
}

// UpdateExitTimezone sets the "exit_timezone" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitTimezone() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitTimezone()
	})
}

// ClearExitTimezone clears the value of the "exit_timezone" field.
func (u *ProxyUpsertOne) ClearExitTimezone() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitTimezone()
	})
}

// SetExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field.
func (u *ProxyUpsertOne) SetExitUtcOffsetSeconds(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitUtcOffsetSeconds(v)
	})
}

// AddExitUtcOffsetSeconds adds v to the "exit_utc_offset_seconds" field.
func (u *ProxyUpsertOne) AddExitUtcOffsetSeconds(v int) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.AddExitUtcOffsetSeconds(v)
	})
}

// UpdateExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitUtcOffsetSeconds() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitUtcOffsetSeconds()
	})
}

// ClearExitUtcOffsetSeconds clears the value of the "exit_utc_offset_seconds" field.
func (u *ProxyUpsertOne) ClearExitUtcOffsetSeconds() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitUtcOffsetSeconds()
	})
}

// SetExitAsn sets the "exit_asn" field.
func (u *ProxyUpsertOne) SetExitAsn(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitAsn(v)
	})
}

// UpdateExitAsn sets the "exit_asn" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitAsn() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitAsn()
	})
}

// ClearExitAsn clears the value of the "exit_asn" field.
func (u *ProxyUpsertOne) ClearExitAsn() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitAsn()
	})
}

// SetExitIsp sets the "exit_isp" field.
func (u *ProxyUpsertOne) SetExitIsp(v string) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitIsp(v)
	})
}

// UpdateExitIsp sets the "exit_isp" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitIsp() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitIsp()
	})
}

// ClearExitIsp clears the value of the "exit_isp" field.
func (u *ProxyUpsertOne) ClearExitIsp() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitIsp()
	})
}

// SetExitCheckedAt sets the "exit_checked_at" field.
func (u *ProxyUpsertOne) SetExitCheckedAt(v time.Time) *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitCheckedAt(v)
	})
}

// UpdateExitCheckedAt sets the "exit_checked_at" field to the value that was provided on create.
func (u *ProxyUpsertOne) UpdateExitCheckedAt() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitCheckedAt()
	})
}

// ClearExitCheckedAt clears the value of the "exit_checked_at" field.
func (u *ProxyUpsertOne) ClearExitCheckedAt() *ProxyUpsertOne {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitCheckedAt()
	})
}

// Exec executes the query.
func (u *ProxyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyCreateBulk is the builder for creating many Proxy entities in bulk.
type ProxyCreateBulk struct {
	config
	err      error
	builders []*ProxyCreate
	conflict []sql.ConflictOption
}

// Save creates the Proxy entities in the database.
func (_c *ProxyCreateBulk) Save(ctx context.Context) ([]*Proxy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Proxy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyCreateBulk) SaveX(ctx context.Context) []*Proxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Proxy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyUpsertBulk {
	_c.conflict = opts
	return &ProxyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Proxy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyCreateBulk) OnConflictColumns(columns ...string) *ProxyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyUpsertBulk{
		create: _c,
	}
}

// ProxyUpsertBulk is the builder for "upsert"-ing
// a bulk of Proxy nodes.
type ProxyUpsertBulk struct {
	create *ProxyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Proxy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyUpsertBulk) UpdateNewValues() *ProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Proxy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyUpsertBulk) Ignore() *ProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyUpsertBulk) DoNothing() *ProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyUpsertBulk) Update(set func(*ProxyUpsert)) *ProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyUpsertBulk) SetUpdatedAt(v time.Time) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateUpdatedAt() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxyUpsertBulk) SetDeletedAt(v time.Time) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateDeletedAt() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxyUpsertBulk) ClearDeletedAt() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ProxyUpsertBulk) SetName(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateName() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateName()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ProxyUpsertBulk) SetProtocol(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateProtocol() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateProtocol()
	})
}

// SetHost sets the "host" field.
func (u *ProxyUpsertBulk) SetHost(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetHost(v)
	})
}

// UpdateHost sets the "host" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateHost() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateHost()
	})
}

// SetPort sets the "port" field.
func (u *ProxyUpsertBulk) SetPort(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetPort(v)
	})
}

// AddPort adds v to the "port" field.
func (u *ProxyUpsertBulk) AddPort(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.AddPort(v)
	})
}

// UpdatePort sets the "port" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdatePort() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdatePort()
	})
}

// SetUsername sets the "username" field.
func (u *ProxyUpsertBulk) SetUsername(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateUsername() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *ProxyUpsertBulk) ClearUsername() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearUsername()
	})
}

// SetPassword sets the "password" field.
func (u *ProxyUpsertBulk) SetPassword(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdatePassword() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdatePassword()
	})
}

// ClearPassword clears the value of the "password" field.
func (u *ProxyUpsertBulk) ClearPassword() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearPassword()
	})
}

// SetStatus sets the "status" field.
func (u *ProxyUpsertBulk) SetStatus(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateStatus() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyUpsertBulk) SetExpiresAt(v time.Time) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExpiresAt() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyUpsertBulk) ClearExpiresAt() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExpiresAt()
	})
}

// SetFallbackMode sets the "fallback_mode" field.
func (u *ProxyUpsertBulk) SetFallbackMode(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetFallbackMode(v)
	})
}

// UpdateFallbackMode sets the "fallback_mode" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateFallbackMode() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateFallbackMode()
	})
}

// SetBackupProxyID sets the "backup_proxy_id" field.
func (u *ProxyUpsertBulk) SetBackupProxyID(v int64) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetBackupProxyID(v)
	})
}

// UpdateBackupProxyID sets the "backup_proxy_id" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateBackupProxyID() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateBackupProxyID()
	})
}

// ClearBackupProxyID clears the value of the "backup_proxy_id" field.
func (u *ProxyUpsertBulk) ClearBackupProxyID() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearBackupProxyID()
	})
}

// SetExpiryWarnDays sets the "expiry_warn_days" field.
func (u *ProxyUpsertBulk) SetExpiryWarnDays(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExpiryWarnDays(v)
	})
}

// AddExpiryWarnDays adds v to the "expiry_warn_days" field.
func (u *ProxyUpsertBulk) AddExpiryWarnDays(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.AddExpiryWarnDays(v)
	})
}

// UpdateExpiryWarnDays sets the "expiry_warn_days" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExpiryWarnDays() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExpiryWarnDays()
	})
}

// SetMaxAccounts sets the "max_accounts" field.
func (u *ProxyUpsertBulk) SetMaxAccounts(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetMaxAccounts(v)
	})
}

// AddMaxAccounts adds v to the "max_accounts" field.
func (u *ProxyUpsertBulk) AddMaxAccounts(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.AddMaxAccounts(v)
	})
}

// UpdateMaxAccounts sets the "max_accounts" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateMaxAccounts() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateMaxAccounts()
	})
}

// SetMaxRpm sets the "max_rpm" field.
func (u *ProxyUpsertBulk) SetMaxRpm(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetMaxRpm(v)
	})
}

// AddMaxRpm adds v to the "max_rpm" field.
func (u *ProxyUpsertBulk) AddMaxRpm(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.AddMaxRpm(v)
	})
}

// UpdateMaxRpm sets the "max_rpm" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateMaxRpm() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateMaxRpm()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *ProxyUpsertBulk) SetMaxConcurrency(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *ProxyUpsertBulk) AddMaxConcurrency(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateMaxConcurrency() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// SetExitIP sets the "exit_ip" field.
func (u *ProxyUpsertBulk) SetExitIP(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitIP(v)
	})
}

// UpdateExitIP sets the "exit_ip" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitIP() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitIP()
	})
}

// ClearExitIP clears the value of the "exit_ip" field.
func (u *ProxyUpsertBulk) ClearExitIP() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitIP()
	})
}

// SetExitCountry sets the "exit_country" field.
func (u *ProxyUpsertBulk) SetExitCountry(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitCountry(v)
	})
}

// UpdateExitCountry sets the "exit_country" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitCountry() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitCountry()
	})
}

// ClearExitCountry clears the value of the "exit_country" field.
func (u *ProxyUpsertBulk) ClearExitCountry() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitCountry()
	})
}

// SetExitCountryCode sets the "exit_country_code" field.
func (u *ProxyUpsertBulk) SetExitCountryCode(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitCountryCode(v)
	})
}

// UpdateExitCountryCode sets the "exit_country_code" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitCountryCode() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitCountryCode()
	})
}

// ClearExitCountryCode clears the value of the "exit_country_code" field.
func (u *ProxyUpsertBulk) ClearExitCountryCode() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitCountryCode()
	})
}

// SetExitRegion sets the "exit_region" field.
func (u *ProxyUpsertBulk) SetExitRegion(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitRegion(v)
	})
}

// UpdateExitRegion sets the "exit_region" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitRegion() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitRegion()
	})
}

// ClearExitRegion clears the value of the "exit_region" field.
func (u *ProxyUpsertBulk) ClearExitRegion() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitRegion()
	})
}

// SetExitCity sets the "exit_city" field.
func (u *ProxyUpsertBulk) SetExitCity(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitCity(v)
	})
}

// UpdateExitCity sets the "exit_city" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitCity() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitCity()
	})
}

// ClearExitCity clears the value of the "exit_city" field.
func (u *ProxyUpsertBulk) ClearExitCity() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitCity()
	})
}

// SetExitTimezone sets the "exit_timezone" field.
func (u *ProxyUpsertBulk) SetExitTimezone(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitTimezone(v)
	})
}

// UpdateExitTimezone sets the "exit_timezone" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitTimezone() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitTimezone()
	})
}

// ClearExitTimezone clears the value of the "exit_timezone" field.
func (u *ProxyUpsertBulk) ClearExitTimezone() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitTimezone()
	})
}

// SetExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field.
func (u *ProxyUpsertBulk) SetExitUtcOffsetSeconds(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitUtcOffsetSeconds(v)
	})
}

// AddExitUtcOffsetSeconds adds v to the "exit_utc_offset_seconds" field.
func (u *ProxyUpsertBulk) AddExitUtcOffsetSeconds(v int) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.AddExitUtcOffsetSeconds(v)
	})
}

// UpdateExitUtcOffsetSeconds sets the "exit_utc_offset_seconds" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitUtcOffsetSeconds() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitUtcOffsetSeconds()
	})
}

// ClearExitUtcOffsetSeconds clears the value of the "exit_utc_offset_seconds" field.
func (u *ProxyUpsertBulk) ClearExitUtcOffsetSeconds() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitUtcOffsetSeconds()
	})
}

// SetExitAsn sets the "exit_asn" field.
func (u *ProxyUpsertBulk) SetExitAsn(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitAsn(v)
	})
}

// UpdateExitAsn sets the "exit_asn" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitAsn() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitAsn()
	})
}

// ClearExitAsn clears the value of the "exit_asn" field.
func (u *ProxyUpsertBulk) ClearExitAsn() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitAsn()
	})
}

// SetExitIsp sets the "exit_isp" field.
func (u *ProxyUpsertBulk) SetExitIsp(v string) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitIsp(v)
	})
}

// UpdateExitIsp sets the "exit_isp" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitIsp() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitIsp()
	})
}

// ClearExitIsp clears the value of the "exit_isp" field.
func (u *ProxyUpsertBulk) ClearExitIsp() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitIsp()
	})
}

// SetExitCheckedAt sets the "exit_checked_at" field.
func (u *ProxyUpsertBulk) SetExitCheckedAt(v time.Time) *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.SetExitCheckedAt(v)
	})
}

// UpdateExitCheckedAt sets the "exit_checked_at" field to the value that was provided on create.
func (u *ProxyUpsertBulk) UpdateExitCheckedAt() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.UpdateExitCheckedAt()
	})
}

// ClearExitCheckedAt clears the value of the "exit_checked_at" field.
func (u *ProxyUpsertBulk) ClearExitCheckedAt() *ProxyUpsertBulk {
	return u.Update(func(s *ProxyUpsert) {
		s.ClearExitCheckedAt()
	})
}

// Exec executes the query.
func (u *ProxyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
