// Code generated by ent, DO NOT EDIT.

package proxy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jk-zhang-meta/berth/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldName, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldProtocol, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldHost, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPort, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPassword, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExpiresAt, v))
}

// FallbackMode applies equality check predicate on the "fallback_mode" field. It's identical to FallbackModeEQ.
func FallbackMode(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldFallbackMode, v))
}

// BackupProxyID applies equality check predicate on the "backup_proxy_id" field. It's identical to BackupProxyIDEQ.
func BackupProxyID(v int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldBackupProxyID, v))
}

// ExpiryWarnDays applies equality check predicate on the "expiry_warn_days" field. It's identical to ExpiryWarnDaysEQ.
func ExpiryWarnDays(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExpiryWarnDays, v))
}

// MaxAccounts applies equality check predicate on the "max_accounts" field. It's identical to MaxAccountsEQ.
func MaxAccounts(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMaxAccounts, v))
}

// MaxRpm applies equality check predicate on the "max_rpm" field. It's identical to MaxRpmEQ.
func MaxRpm(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMaxRpm, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMaxConcurrency, v))
}

// ExitIP applies equality check predicate on the "exit_ip" field. It's identical to ExitIPEQ.
func ExitIP(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitIP, v))
}

// ExitCountry applies equality check predicate on the "exit_country" field. It's identical to ExitCountryEQ.
func ExitCountry(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitCountry, v))
}

// ExitCountryCode applies equality check predicate on the "exit_country_code" field. It's identical to ExitCountryCodeEQ.
func ExitCountryCode(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitCountryCode, v))
}

// ExitRegion applies equality check predicate on the "exit_region" field. It's identical to ExitRegionEQ.
func ExitRegion(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitRegion, v))
}

// ExitCity applies equality check predicate on the "exit_city" field. It's identical to ExitCityEQ.
func ExitCity(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitCity, v))
}

// ExitTimezone applies equality check predicate on the "exit_timezone" field. It's identical to ExitTimezoneEQ.
func ExitTimezone(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitTimezone, v))
}

// ExitUtcOffsetSeconds applies equality check predicate on the "exit_utc_offset_seconds" field. It's identical to ExitUtcOffsetSecondsEQ.
func ExitUtcOffsetSeconds(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitUtcOffsetSeconds, v))
}

// ExitAsn applies equality check predicate on the "exit_asn" field. It's identical to ExitAsnEQ.
func ExitAsn(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitAsn, v))
}

// ExitIsp applies equality check predicate on the "exit_isp" field. It's identical to ExitIspEQ.
func ExitIsp(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitIsp, v))
}

// ExitCheckedAt applies equality check predicate on the "exit_checked_at" field. It's identical to ExitCheckedAtEQ.
func ExitCheckedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitCheckedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldName, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldProtocol, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldHost, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldPort, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldPassword, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExpiresAt))
}

// FallbackModeEQ applies the EQ predicate on the "fallback_mode" field.
func FallbackModeEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldFallbackMode, v))
}

// FallbackModeNEQ applies the NEQ predicate on the "fallback_mode" field.
func FallbackModeNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldFallbackMode, v))
}

// FallbackModeIn applies the In predicate on the "fallback_mode" field.
func FallbackModeIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldFallbackMode, vs...))
}

// FallbackModeNotIn applies the NotIn predicate on the "fallback_mode" field.
func FallbackModeNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldFallbackMode, vs...))
}

// FallbackModeGT applies the GT predicate on the "fallback_mode" field.
func FallbackModeGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldFallbackMode, v))
}

// FallbackModeGTE applies the GTE predicate on the "fallback_mode" field.
func FallbackModeGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldFallbackMode, v))
}

// FallbackModeLT applies the LT predicate on the "fallback_mode" field.
func FallbackModeLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldFallbackMode, v))
}

// FallbackModeLTE applies the LTE predicate on the "fallback_mode" field.
func FallbackModeLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldFallbackMode, v))
}

// FallbackModeContains applies the Contains predicate on the "fallback_mode" field.
func FallbackModeContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldFallbackMode, v))
}

// FallbackModeHasPrefix applies the HasPrefix predicate on the "fallback_mode" field.
func FallbackModeHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldFallbackMode, v))
}

// FallbackModeHasSuffix applies the HasSuffix predicate on the "fallback_mode" field.
func FallbackModeHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldFallbackMode, v))
}

// FallbackModeEqualFold applies the EqualFold predicate on the "fallback_mode" field.
func FallbackModeEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldFallbackMode, v))
}

// FallbackModeContainsFold applies the ContainsFold predicate on the "fallback_mode" field.
func FallbackModeContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldFallbackMode, v))
}

// BackupProxyIDEQ applies the EQ predicate on the "backup_proxy_id" field.
func BackupProxyIDEQ(v int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldBackupProxyID, v))
}

// BackupProxyIDNEQ applies the NEQ predicate on the "backup_proxy_id" field.
func BackupProxyIDNEQ(v int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldBackupProxyID, v))
}

// BackupProxyIDIn applies the In predicate on the "backup_proxy_id" field.
func BackupProxyIDIn(vs ...int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldBackupProxyID, vs...))
}

// BackupProxyIDNotIn applies the NotIn predicate on the "backup_proxy_id" field.
func BackupProxyIDNotIn(vs ...int64) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldBackupProxyID, vs...))
}

// BackupProxyIDIsNil applies the IsNil predicate on the "backup_proxy_id" field.
func BackupProxyIDIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldBackupProxyID))
}

// BackupProxyIDNotNil applies the NotNil predicate on the "backup_proxy_id" field.
func BackupProxyIDNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldBackupProxyID))
}

// ExpiryWarnDaysEQ applies the EQ predicate on the "expiry_warn_days" field.
func ExpiryWarnDaysEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExpiryWarnDays, v))
}

// ExpiryWarnDaysNEQ applies the NEQ predicate on the "expiry_warn_days" field.
func ExpiryWarnDaysNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExpiryWarnDays, v))
}

// ExpiryWarnDaysIn applies the In predicate on the "expiry_warn_days" field.
func ExpiryWarnDaysIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExpiryWarnDays, vs...))
}

// ExpiryWarnDaysNotIn applies the NotIn predicate on the "expiry_warn_days" field.
func ExpiryWarnDaysNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExpiryWarnDays, vs...))
}

// ExpiryWarnDaysGT applies the GT predicate on the "expiry_warn_days" field.
func ExpiryWarnDaysGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExpiryWarnDays, v))
}

// ExpiryWarnDaysGTE applies the GTE predicate on the "expiry_warn_days" field.
func ExpiryWarnDaysGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExpiryWarnDays, v))
}

// ExpiryWarnDaysLT applies the LT predicate on the "expiry_warn_days" field.
func ExpiryWarnDaysLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExpiryWarnDays, v))
}

// ExpiryWarnDaysLTE applies the LTE predicate on the "expiry_warn_days" field.
func ExpiryWarnDaysLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExpiryWarnDays, v))
}

// MaxAccountsEQ applies the EQ predicate on the "max_accounts" field.
func MaxAccountsEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMaxAccounts, v))
}

// MaxAccountsNEQ applies the NEQ predicate on the "max_accounts" field.
func MaxAccountsNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldMaxAccounts, v))
}

// MaxAccountsIn applies the In predicate on the "max_accounts" field.
func MaxAccountsIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldMaxAccounts, vs...))
}

// MaxAccountsNotIn applies the NotIn predicate on the "max_accounts" field.
func MaxAccountsNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldMaxAccounts, vs...))
}

// MaxAccountsGT applies the GT predicate on the "max_accounts" field.
func MaxAccountsGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldMaxAccounts, v))
}

// MaxAccountsGTE applies the GTE predicate on the "max_accounts" field.
func MaxAccountsGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldMaxAccounts, v))
}

// MaxAccountsLT applies the LT predicate on the "max_accounts" field.
func MaxAccountsLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldMaxAccounts, v))
}

// MaxAccountsLTE applies the LTE predicate on the "max_accounts" field.
func MaxAccountsLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldMaxAccounts, v))
}

// MaxRpmEQ applies the EQ predicate on the "max_rpm" field.
func MaxRpmEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMaxRpm, v))
}

// MaxRpmNEQ applies the NEQ predicate on the "max_rpm" field.
func MaxRpmNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldMaxRpm, v))
}

// MaxRpmIn applies the In predicate on the "max_rpm" field.
func MaxRpmIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldMaxRpm, vs...))
}

// MaxRpmNotIn applies the NotIn predicate on the "max_rpm" field.
func MaxRpmNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldMaxRpm, vs...))
}

// MaxRpmGT applies the GT predicate on the "max_rpm" field.
func MaxRpmGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldMaxRpm, v))
}

// MaxRpmGTE applies the GTE predicate on the "max_rpm" field.
func MaxRpmGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldMaxRpm, v))
}

// MaxRpmLT applies the LT predicate on the "max_rpm" field.
func MaxRpmLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldMaxRpm, v))
}

// MaxRpmLTE applies the LTE predicate on the "max_rpm" field.
func MaxRpmLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldMaxRpm, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldMaxConcurrency, v))
}

// ExitIPEQ applies the EQ predicate on the "exit_ip" field.
func ExitIPEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitIP, v))
}

// ExitIPNEQ applies the NEQ predicate on the "exit_ip" field.
func ExitIPNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitIP, v))
}

// ExitIPIn applies the In predicate on the "exit_ip" field.
func ExitIPIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitIP, vs...))
}

// ExitIPNotIn applies the NotIn predicate on the "exit_ip" field.
func ExitIPNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitIP, vs...))
}

// ExitIPGT applies the GT predicate on the "exit_ip" field.
func ExitIPGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitIP, v))
}

// ExitIPGTE applies the GTE predicate on the "exit_ip" field.
func ExitIPGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitIP, v))
}

// ExitIPLT applies the LT predicate on the "exit_ip" field.
func ExitIPLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitIP, v))
}

// ExitIPLTE applies the LTE predicate on the "exit_ip" field.
func ExitIPLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitIP, v))
}

// ExitIPContains applies the Contains predicate on the "exit_ip" field.
func ExitIPContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitIP, v))
}

// ExitIPHasPrefix applies the HasPrefix predicate on the "exit_ip" field.
func ExitIPHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitIP, v))
}

// ExitIPHasSuffix applies the HasSuffix predicate on the "exit_ip" field.
func ExitIPHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitIP, v))
}

// ExitIPIsNil applies the IsNil predicate on the "exit_ip" field.
func ExitIPIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitIP))
}

// ExitIPNotNil applies the NotNil predicate on the "exit_ip" field.
func ExitIPNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitIP))
}

// ExitIPEqualFold applies the EqualFold predicate on the "exit_ip" field.
func ExitIPEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitIP, v))
}

// ExitIPContainsFold applies the ContainsFold predicate on the "exit_ip" field.
func ExitIPContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitIP, v))
}

// ExitCountryEQ applies the EQ predicate on the "exit_country" field.
func ExitCountryEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitCountry, v))
}

// ExitCountryNEQ applies the NEQ predicate on the "exit_country" field.
func ExitCountryNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitCountry, v))
}

// ExitCountryIn applies the In predicate on the "exit_country" field.
func ExitCountryIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitCountry, vs...))
}

// ExitCountryNotIn applies the NotIn predicate on the "exit_country" field.
func ExitCountryNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitCountry, vs...))
}

// ExitCountryGT applies the GT predicate on the "exit_country" field.
func ExitCountryGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitCountry, v))
}

// ExitCountryGTE applies the GTE predicate on the "exit_country" field.
func ExitCountryGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitCountry, v))
}

// ExitCountryLT applies the LT predicate on the "exit_country" field.
func ExitCountryLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitCountry, v))
}

// ExitCountryLTE applies the LTE predicate on the "exit_country" field.
func ExitCountryLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitCountry, v))
}

// ExitCountryContains applies the Contains predicate on the "exit_country" field.
func ExitCountryContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitCountry, v))
}

// ExitCountryHasPrefix applies the HasPrefix predicate on the "exit_country" field.
func ExitCountryHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitCountry, v))
}

// ExitCountryHasSuffix applies the HasSuffix predicate on the "exit_country" field.
func ExitCountryHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitCountry, v))
}

// ExitCountryIsNil applies the IsNil predicate on the "exit_country" field.
func ExitCountryIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitCountry))
}

// ExitCountryNotNil applies the NotNil predicate on the "exit_country" field.
func ExitCountryNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitCountry))
}

// ExitCountryEqualFold applies the EqualFold predicate on the "exit_country" field.
func ExitCountryEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitCountry, v))
}

// ExitCountryContainsFold applies the ContainsFold predicate on the "exit_country" field.
func ExitCountryContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitCountry, v))
}

// ExitCountryCodeEQ applies the EQ predicate on the "exit_country_code" field.
func ExitCountryCodeEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitCountryCode, v))
}

// ExitCountryCodeNEQ applies the NEQ predicate on the "exit_country_code" field.
func ExitCountryCodeNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitCountryCode, v))
}

// ExitCountryCodeIn applies the In predicate on the "exit_country_code" field.
func ExitCountryCodeIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitCountryCode, vs...))
}

// ExitCountryCodeNotIn applies the NotIn predicate on the "exit_country_code" field.
func ExitCountryCodeNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitCountryCode, vs...))
}

// ExitCountryCodeGT applies the GT predicate on the "exit_country_code" field.
func ExitCountryCodeGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitCountryCode, v))
}

// ExitCountryCodeGTE applies the GTE predicate on the "exit_country_code" field.
func ExitCountryCodeGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitCountryCode, v))
}

// ExitCountryCodeLT applies the LT predicate on the "exit_country_code" field.
func ExitCountryCodeLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitCountryCode, v))
}

// ExitCountryCodeLTE applies the LTE predicate on the "exit_country_code" field.
func ExitCountryCodeLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitCountryCode, v))
}

// ExitCountryCodeContains applies the Contains predicate on the "exit_country_code" field.
func ExitCountryCodeContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitCountryCode, v))
}

// ExitCountryCodeHasPrefix applies the HasPrefix predicate on the "exit_country_code" field.
func ExitCountryCodeHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitCountryCode, v))
}

// ExitCountryCodeHasSuffix applies the HasSuffix predicate on the "exit_country_code" field.
func ExitCountryCodeHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitCountryCode, v))
}

// ExitCountryCodeIsNil applies the IsNil predicate on the "exit_country_code" field.
func ExitCountryCodeIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitCountryCode))
}

// ExitCountryCodeNotNil applies the NotNil predicate on the "exit_country_code" field.
func ExitCountryCodeNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitCountryCode))
}

// ExitCountryCodeEqualFold applies the EqualFold predicate on the "exit_country_code" field.
func ExitCountryCodeEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitCountryCode, v))
}

// ExitCountryCodeContainsFold applies the ContainsFold predicate on the "exit_country_code" field.
func ExitCountryCodeContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitCountryCode, v))
}

// ExitRegionEQ applies the EQ predicate on the "exit_region" field.
func ExitRegionEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitRegion, v))
}

// ExitRegionNEQ applies the NEQ predicate on the "exit_region" field.
func ExitRegionNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitRegion, v))
}

// ExitRegionIn applies the In predicate on the "exit_region" field.
func ExitRegionIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitRegion, vs...))
}

// ExitRegionNotIn applies the NotIn predicate on the "exit_region" field.
func ExitRegionNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitRegion, vs...))
}

// ExitRegionGT applies the GT predicate on the "exit_region" field.
func ExitRegionGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitRegion, v))
}

// ExitRegionGTE applies the GTE predicate on the "exit_region" field.
func ExitRegionGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitRegion, v))
}

// ExitRegionLT applies the LT predicate on the "exit_region" field.
func ExitRegionLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitRegion, v))
}

// ExitRegionLTE applies the LTE predicate on the "exit_region" field.
func ExitRegionLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitRegion, v))
}

// ExitRegionContains applies the Contains predicate on the "exit_region" field.
func ExitRegionContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitRegion, v))
}

// ExitRegionHasPrefix applies the HasPrefix predicate on the "exit_region" field.
func ExitRegionHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitRegion, v))
}

// ExitRegionHasSuffix applies the HasSuffix predicate on the "exit_region" field.
func ExitRegionHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitRegion, v))
}

// ExitRegionIsNil applies the IsNil predicate on the "exit_region" field.
func ExitRegionIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitRegion))
}

// ExitRegionNotNil applies the NotNil predicate on the "exit_region" field.
func ExitRegionNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitRegion))
}

// ExitRegionEqualFold applies the EqualFold predicate on the "exit_region" field.
func ExitRegionEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitRegion, v))
}

// ExitRegionContainsFold applies the ContainsFold predicate on the "exit_region" field.
func ExitRegionContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitRegion, v))
}

// ExitCityEQ applies the EQ predicate on the "exit_city" field.
func ExitCityEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitCity, v))
}

// ExitCityNEQ applies the NEQ predicate on the "exit_city" field.
func ExitCityNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitCity, v))
}

// ExitCityIn applies the In predicate on the "exit_city" field.
func ExitCityIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitCity, vs...))
}

// ExitCityNotIn applies the NotIn predicate on the "exit_city" field.
func ExitCityNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitCity, vs...))
}

// ExitCityGT applies the GT predicate on the "exit_city" field.
func ExitCityGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitCity, v))
}

// ExitCityGTE applies the GTE predicate on the "exit_city" field.
func ExitCityGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitCity, v))
}

// ExitCityLT applies the LT predicate on the "exit_city" field.
func ExitCityLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitCity, v))
}

// ExitCityLTE applies the LTE predicate on the "exit_city" field.
func ExitCityLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitCity, v))
}

// ExitCityContains applies the Contains predicate on the "exit_city" field.
func ExitCityContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitCity, v))
}

// ExitCityHasPrefix applies the HasPrefix predicate on the "exit_city" field.
func ExitCityHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitCity, v))
}

// ExitCityHasSuffix applies the HasSuffix predicate on the "exit_city" field.
func ExitCityHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitCity, v))
}

// ExitCityIsNil applies the IsNil predicate on the "exit_city" field.
func ExitCityIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitCity))
}

// ExitCityNotNil applies the NotNil predicate on the "exit_city" field.
func ExitCityNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitCity))
}

// ExitCityEqualFold applies the EqualFold predicate on the "exit_city" field.
func ExitCityEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitCity, v))
}

// ExitCityContainsFold applies the ContainsFold predicate on the "exit_city" field.
func ExitCityContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitCity, v))
}

// ExitTimezoneEQ applies the EQ predicate on the "exit_timezone" field.
func ExitTimezoneEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitTimezone, v))
}

// ExitTimezoneNEQ applies the NEQ predicate on the "exit_timezone" field.
func ExitTimezoneNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitTimezone, v))
}

// ExitTimezoneIn applies the In predicate on the "exit_timezone" field.
func ExitTimezoneIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitTimezone, vs...))
}

// ExitTimezoneNotIn applies the NotIn predicate on the "exit_timezone" field.
func ExitTimezoneNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitTimezone, vs...))
}

// ExitTimezoneGT applies the GT predicate on the "exit_timezone" field.
func ExitTimezoneGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitTimezone, v))
}

// ExitTimezoneGTE applies the GTE predicate on the "exit_timezone" field.
func ExitTimezoneGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitTimezone, v))
}

// ExitTimezoneLT applies the LT predicate on the "exit_timezone" field.
func ExitTimezoneLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitTimezone, v))
}

// ExitTimezoneLTE applies the LTE predicate on the "exit_timezone" field.
func ExitTimezoneLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitTimezone, v))
}

// ExitTimezoneContains applies the Contains predicate on the "exit_timezone" field.
func ExitTimezoneContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitTimezone, v))
}

// ExitTimezoneHasPrefix applies the HasPrefix predicate on the "exit_timezone" field.
func ExitTimezoneHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitTimezone, v))
}

// ExitTimezoneHasSuffix applies the HasSuffix predicate on the "exit_timezone" field.
func ExitTimezoneHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitTimezone, v))
}

// ExitTimezoneIsNil applies the IsNil predicate on the "exit_timezone" field.
func ExitTimezoneIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitTimezone))
}

// ExitTimezoneNotNil applies the NotNil predicate on the "exit_timezone" field.
func ExitTimezoneNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitTimezone))
}

// ExitTimezoneEqualFold applies the EqualFold predicate on the "exit_timezone" field.
func ExitTimezoneEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitTimezone, v))
}

// ExitTimezoneContainsFold applies the ContainsFold predicate on the "exit_timezone" field.
func ExitTimezoneContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitTimezone, v))
}

// ExitUtcOffsetSecondsEQ applies the EQ predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitUtcOffsetSeconds, v))
}

// ExitUtcOffsetSecondsNEQ applies the NEQ predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitUtcOffsetSeconds, v))
}

// ExitUtcOffsetSecondsIn applies the In predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitUtcOffsetSeconds, vs...))
}

// ExitUtcOffsetSecondsNotIn applies the NotIn predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitUtcOffsetSeconds, vs...))
}

// ExitUtcOffsetSecondsGT applies the GT predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitUtcOffsetSeconds, v))
}

// ExitUtcOffsetSecondsGTE applies the GTE predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitUtcOffsetSeconds, v))
}

// ExitUtcOffsetSecondsLT applies the LT predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitUtcOffsetSeconds, v))
}

// ExitUtcOffsetSecondsLTE applies the LTE predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitUtcOffsetSeconds, v))
}

// ExitUtcOffsetSecondsIsNil applies the IsNil predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitUtcOffsetSeconds))
}

// ExitUtcOffsetSecondsNotNil applies the NotNil predicate on the "exit_utc_offset_seconds" field.
func ExitUtcOffsetSecondsNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitUtcOffsetSeconds))
}

// ExitAsnEQ applies the EQ predicate on the "exit_asn" field.
func ExitAsnEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitAsn, v))
}

// ExitAsnNEQ applies the NEQ predicate on the "exit_asn" field.
func ExitAsnNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitAsn, v))
}

// ExitAsnIn applies the In predicate on the "exit_asn" field.
func ExitAsnIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitAsn, vs...))
}

// ExitAsnNotIn applies the NotIn predicate on the "exit_asn" field.
func ExitAsnNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitAsn, vs...))
}

// ExitAsnGT applies the GT predicate on the "exit_asn" field.
func ExitAsnGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitAsn, v))
}

// ExitAsnGTE applies the GTE predicate on the "exit_asn" field.
func ExitAsnGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitAsn, v))
}

// ExitAsnLT applies the LT predicate on the "exit_asn" field.
func ExitAsnLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitAsn, v))
}

// ExitAsnLTE applies the LTE predicate on the "exit_asn" field.
func ExitAsnLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitAsn, v))
}

// ExitAsnContains applies the Contains predicate on the "exit_asn" field.
func ExitAsnContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitAsn, v))
}

// ExitAsnHasPrefix applies the HasPrefix predicate on the "exit_asn" field.
func ExitAsnHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitAsn, v))
}

// ExitAsnHasSuffix applies the HasSuffix predicate on the "exit_asn" field.
func ExitAsnHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitAsn, v))
}

// ExitAsnIsNil applies the IsNil predicate on the "exit_asn" field.
func ExitAsnIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitAsn))
}

// ExitAsnNotNil applies the NotNil predicate on the "exit_asn" field.
func ExitAsnNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitAsn))
}

// ExitAsnEqualFold applies the EqualFold predicate on the "exit_asn" field.
func ExitAsnEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitAsn, v))
}

// ExitAsnContainsFold applies the ContainsFold predicate on the "exit_asn" field.
func ExitAsnContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitAsn, v))
}

// ExitIspEQ applies the EQ predicate on the "exit_isp" field.
func ExitIspEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitIsp, v))
}

// ExitIspNEQ applies the NEQ predicate on the "exit_isp" field.
func ExitIspNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitIsp, v))
}

// ExitIspIn applies the In predicate on the "exit_isp" field.
func ExitIspIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitIsp, vs...))
}

// ExitIspNotIn applies the NotIn predicate on the "exit_isp" field.
func ExitIspNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitIsp, vs...))
}

// ExitIspGT applies the GT predicate on the "exit_isp" field.
func ExitIspGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitIsp, v))
}

// ExitIspGTE applies the GTE predicate on the "exit_isp" field.
func ExitIspGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitIsp, v))
}

// ExitIspLT applies the LT predicate on the "exit_isp" field.
func ExitIspLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitIsp, v))
}

// ExitIspLTE applies the LTE predicate on the "exit_isp" field.
func ExitIspLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitIsp, v))
}

// ExitIspContains applies the Contains predicate on the "exit_isp" field.
func ExitIspContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldExitIsp, v))
}

// ExitIspHasPrefix applies the HasPrefix predicate on the "exit_isp" field.
func ExitIspHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldExitIsp, v))
}

// ExitIspHasSuffix applies the HasSuffix predicate on the "exit_isp" field.
func ExitIspHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldExitIsp, v))
}

// ExitIspIsNil applies the IsNil predicate on the "exit_isp" field.
func ExitIspIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitIsp))
}

// ExitIspNotNil applies the NotNil predicate on the "exit_isp" field.
func ExitIspNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitIsp))
}

// ExitIspEqualFold applies the EqualFold predicate on the "exit_isp" field.
func ExitIspEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldExitIsp, v))
}

// ExitIspContainsFold applies the ContainsFold predicate on the "exit_isp" field.
func ExitIspContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldExitIsp, v))
}

// ExitCheckedAtEQ applies the EQ predicate on the "exit_checked_at" field.
func ExitCheckedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldExitCheckedAt, v))
}

// ExitCheckedAtNEQ applies the NEQ predicate on the "exit_checked_at" field.
func ExitCheckedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldExitCheckedAt, v))
}

// ExitCheckedAtIn applies the In predicate on the "exit_checked_at" field.
func ExitCheckedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldExitCheckedAt, vs...))
}

// ExitCheckedAtNotIn applies the NotIn predicate on the "exit_checked_at" field.
func ExitCheckedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldExitCheckedAt, vs...))
}

// ExitCheckedAtGT applies the GT predicate on the "exit_checked_at" field.
func ExitCheckedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldExitCheckedAt, v))
}

// ExitCheckedAtGTE applies the GTE predicate on the "exit_checked_at" field.
func ExitCheckedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldExitCheckedAt, v))
}

// ExitCheckedAtLT applies the LT predicate on the "exit_checked_at" field.
func ExitCheckedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldExitCheckedAt, v))
}

// ExitCheckedAtLTE applies the LTE predicate on the "exit_checked_at" field.
func ExitCheckedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldExitCheckedAt, v))
}

// ExitCheckedAtIsNil applies the IsNil predicate on the "exit_checked_at" field.
func ExitCheckedAtIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExitCheckedAt))
}

// ExitCheckedAtNotNil applies the NotNil predicate on the "exit_checked_at" field.
func ExitCheckedAtNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExitCheckedAt))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPrimaryProxies applies the HasEdge predicate on the "primary_proxies" edge.
func HasPrimaryProxies() predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, PrimaryProxiesTable, PrimaryProxiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrimaryProxiesWith applies the HasEdge predicate on the "primary_proxies" edge with a given conditions (other predicates).
func HasPrimaryProxiesWith(preds ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := newPrimaryProxiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBackupProxy applies the HasEdge predicate on the "backup_proxy" edge.
func HasBackupProxy() predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, BackupProxyTable, BackupProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBackupProxyWith applies the HasEdge predicate on the "backup_proxy" edge with a given conditions (other predicates).
func HasBackupProxyWith(preds ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := newBackupProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.NotPredicates(p))
}
